docs/guide/use/guide/locations/index.md, docs/style/css/base.scss, usage/archetypes/quickstart/src/brooklyn-sample/src/main/assembly/files/README.txt
* Update links
* Offset anchors so they are visible below the fixed header
There is still some problem with the breadcrumbs (i.e. https://brooklyn.incubator.apache.org/v/latest/use/examples/webcluster/index.html), though locally they work fine, so couldn't troubleshoot it - could it be just a problem with the last generation?
=> Public site fixes

software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java, software/base/src/test/java/brooklyn/entity/basic/lifecycle/ScriptHelperTest.java
Fixes "Caused by: java.lang.IllegalStateException: Timeout waiting for SERVICE_UP from MyServiceImpl" frequently sabotaging the windows CI build.
MyServiceImpl is setting SERVICE_UP manually while the enrichers toggle it in parallel in response to the SERVICE_STATE_ACTUAL changes. Sometimes the enricher will trigger in the window between MyServiceImpl setting the value to true and calling waitForServiceUp, leading to the timeout error.
=> Fixes SERVICE_UP timeout error in tests

docs/_build/build.sh, docs/_build/make-javadoc.sh, docs/_build/quick-make-few-javadoc.sh, locations/jclouds/src/main/resources/sample/script/setup-server.sh, usage/all/start-mgmt-web.sh, usage/dist/src/main/dist/bin/brooklyn, usage/scripts/change-version.sh, usage/scripts/grep-in-poms.sh
expand on b20f45fbbc05950b27004b922182b3390fa7a727 applying to all scripts where relevant
@jimjag thanks for your fix ^^^.  does this make sense, applying it everywhere?
=> use env to find bash in scripts

api/src/main/java/brooklyn/catalog/BrooklynCatalog.java, core/src/main/java/brooklyn/catalog/CatalogPredicates.java, core/src/main/java/brooklyn/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/brooklyn/catalog/internal/CatalogItemComparator.java, usage/jsgui/src/main/webapp/assets/js/view/entity-summary.js, usage/jsgui/src/main/webapp/assets/tpl/apps/summary.html, usage/rest-server/src/main/java/brooklyn/rest/resources/CatalogResource.java, usage/rest-server/src/main/java/brooklyn/rest/transform/EntityTransformer.java, usage/rest-server/src/main/java/brooklyn/rest/util/BrooklynRestResourceUtils.java, usage/rest-server/src/main/java/brooklyn/rest/util/WebResourceUtils.java, usage/rest-server/src/test/java/brooklyn/rest/util/BrooklynRestResourceUtilsTest.java
* Correctly load java classes from the catalog (legacy mechanism), taking into account versioning precedence.
* Tag the resulting entities with the catalogItemId used for loading.
* Fix the catalog link in rest response.
* Fix the UI link to catalog items for applications.
=> Fix - legacy catalog items versioning

docs/_build/make-javadoc.sh
Three changes:
1. `BROOKLYN_VERSION` annotation to ensure that 0.7.0-SNAPSHOT reference is updated.
2. Javadoc output spews out a lot of noise to stdout and errors/warnings to stderr, but use of `tee` saves only stdout noise and not the useful error messages - changed to send errors to stdout, and what was stdout goes to /dev/null.
3. Abort if the required brooklyn-all-dependencies jar file has not been built.
=> Fixes to make_javadoc.sh script

docs/Gemfile, docs/Gemfile.lock, docs/_build/build.sh
Swaps the link-checker gem for html-proofer, which can check [quite a lot more](https://github.com/gjtorikian/html-proofer#whats-tested). Incorporated the tool into `build.sh` and added option to skip with `--skip-tests`.
Also replaces all uses of "brooklyn" with "Brooklyn".
=> Documentation link check improvements

usage/jsgui/pom.xml, usage/jsgui/src/main/assembly/assembly.xml, usage/launcher/pom.xml
Wrap the console war in a standalone jar so it can easiliy be excluded from downstream projects (and overriden with custom build) without needing to customize the launcher.
In a downstream project to use custom jsgui:
```
<dependency>
<groupId>io.apache.brooklyn</groupId>
<artifactId>brooklyn-all</artifactId>
<version>${brooklyn.version}</version>
<exclusions>
<exclusion>
<artifactId>brooklyn-jsgui</artifactId>
<groupId>org.apache.brooklyn</groupId>
</exclusion>
</exclusions>
</dependency>
<dependency>
<groupId>io.downstream</groupId>
<artifactId>custom-jsgui</artifactId>
<version>0.1.0-SNAPSHOT</version>
<classifier>war</classifier>
<exclusions>
<exclusion>
<artifactId>brooklyn-jsgui</artifactId>
<groupId>org.apache.brooklyn</groupId>
</exclusion>
</exclusions>
</dependency>
```
=> Standalone console dependency

core/src/main/java/brooklyn/entity/basic/BrooklynConfigKeys.java, core/src/main/java/brooklyn/event/basic/PortAttributeSensorAndConfigKey.java, software/base/src/main/java/brooklyn/entity/basic/AbstractSoftwareProcessDriver.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcess.java
Add check if entity is already running before skipping startup. Also allows setting the configuration for skip of startup and install on the location, useful when known good images are being used in a fixed IP byon location or an on premises cloud.
=> Add configuration to skip start if entity already running

core/src/main/java/brooklyn/management/ha/OsgiManager.java, core/src/test/resources/brooklyn/camp/lite/test-app-service-blueprint.yaml, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java
Bundles are always matched by their symbolicName and version, not by the user specified alternatives, so allowing them to diverge will lead to unexpected behaviour. So far the logic was to fail only if the bundle is already installed which was inconsistent with first-time install when it would pass.
=> Catalog libs - fail if user specified symbolicName and version don't match bundle

software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessDriverLifecycleEffectorTasks.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java, software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
* Allow entities to be able to abort their stop effector. If pre-stop is aborted the machine will still be released.
* Unmanage BrooklynNode on stop
WARNING: Turns out that postStop wasn't wired up, it was never called. Nevertheless some entities (i.e. CouchDBNode, NginxController, JavaWebAppSoftwareProcess) override it which might introduce unwanted behaviour. Shall I remove the override in existing entities?
=> BrooklynNode - unmanage on stop, fix abort logic

core/src/main/java/brooklyn/entity/basic/BrooklynTaskTags.java, core/src/main/java/brooklyn/management/internal/EffectorUtils.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessDriverLifecycleEffectorTasks.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java, software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/main/java/brooklyn/entity/brooklynnode/effector/BrooklynNodeUpgradeEffectorBody.java, software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
The shutdown effector was setting a STOP state which prevented the machine from being released.
Changes:
* Convert the shutdown effector as a utility functionality - just call the remote shutdown endpoint with the passed parameters
* Store effector parameters in the EffectorCallTag, methods calls to fetch them. Passing the parameters along the call chain would cause backwards incompatible changes.
* Pass stop parameters to the shutdown effector so that it's functionality can be fine tuned by calling stop directly
* Don't unamange the node if the machine is not released.
* Add logic to wait for the graceful shutdown of the process before killing it forcibly (the java process will take some time to shut down cleanly after closing the rest connection)
Depends on …
=> Release the underlying machine when stopping BrooklynNode

usage/rest-client/src/main/java/brooklyn/rest/client/BrooklynApi.java, usage/rest-client/src/test/java/brooklyn/rest/client/BrooklynApiRestClientTest.java
The `BrooklynApi` class in the rest-client module can authenticate to Brooklyn servers.
=> Rest client authenticates

usage/scripts/change-version.sh
* Remove the usage of pcregrep which is not installed by default on OS X or Linux.
* Support for passing the version marker as an argument.
* Simplify the code, no need for loops.
=> Improve change-version.sh script

core/src/main/java/brooklyn/location/basic/SshMachineLocation.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
Adds new configkey for controlling automatic detection of machine details. Defaults to true (matching previous behaviour); setting to false stops SshMachineLocation opening up an SSH channel and running commands. Useful in situations where the application requires strict control over the use of SSH.
=> DETECT_MACHINE_DETAILS SshMachineLocation config

software/messaging/src/main/java/brooklyn/entity/messaging/activemq/ActiveMQBroker.java
All tests in `ActiveMQIntegrationTest` pass.
=> ActiveMQ version is now 5.10.1.

core/src/main/java/brooklyn/util/file/ArchiveUtils.java
Fix for [BROOKLYN-129](https://issues.apache.org/jira/browse/BROOKLYN-129): issue install commands with guarded destFile instead of optionalDestFile.
=> fixed BROOKLYN-128: ArchiveUtils ignores destFile, prefers optionalDestFile during deploy

software/webapp/src/main/resources/brooklyn/entity/webapp/jboss/jboss7-standalone.xml, software/webapp/src/main/resources/brooklyn/entity/webapp/tomcat/server.xml, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java, usage/launcher/src/test/java/brooklyn/launcher/BrooklynWebServerTest.java, usage/launcher/src/test/java/brooklyn/launcher/WebAppRunnerTest.java
Also enable `$brooklyn:object` to use TypeCoercions enabled objects (i.e. for objects that don't have setters). This allows one to use:
```
services:
- type: brooklyn.entity.webapp.jboss.JBoss7Server
brooklyn.config:
webapp.enabledProtocols: ["https"]
webapp.https.ssl:
$brooklyn:object:
objectType: brooklyn.entity.webapp.HttpsSslConfig
object.fields:
keystoreUrl: https://artifactory:AP5QT5YLhmBu3ET9Qe8wwkrNs3r@artifactory.mms.ibmcloud.com/artifactory/thirdparty/certs/faisalssaph1_keystore
keystorePassword: changeit
keyAlias: amm
```
=> Disable SSLv3

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationTemplateOptionsCustomisersLiveTest.java
Adds new config key for JcloudsLocation, templateOptions, that takes a Map<String,String> for setting arbitrary template options. For each entry, searches for a method with the same name as the key, with a single parameter that TypeCoercions supports. The method is then invoked with the value. If such a method cannot be found, then a warning is printed to the log.
The config key's value can be expressed as a YAML fragment in blueprints or in brooklyn.properties:
```properties
brooklyn.location.named.softlayer-ams01.templateOptions={ domainName: 'example.com' }
```
```yaml
location:
jclouds:softlayer:ams01:
templateOptions:
domainName: 'example.com'
```
=> JcloudsLocation set arbitrary template options

utils/common/src/main/java/brooklyn/util/net/Urls.java, utils/common/src/test/java/brooklyn/util/net/UrlsTest.java
Fix for [BROOKLYN-129](https://issues.apache.org/jira/browse/BROOKLYN-129): filter nulls before iterating through path parts.
=> brooklyn.util.net.Urls.mergePaths(String... items) mishandles nulls in input path parts

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
If jclouds node doesn’t know its operatingSystem, then was
getting NPE. Guard against that, and default to unix.
=> JcloudsLocation: avoid NPE on user-creation

core/src/main/java/brooklyn/entity/basic/ConfigKeys.java, core/src/main/java/brooklyn/entity/basic/EntityConfigMap.java, core/src/main/java/brooklyn/entity/basic/ServiceStateLogic.java, core/src/main/java/brooklyn/event/basic/BasicConfigKey.java, core/src/main/java/brooklyn/location/basic/AbstractLocation.java, core/src/main/java/brooklyn/location/basic/LocationInternal.java, core/src/test/java/brooklyn/entity/basic/ConfigEntityInheritanceTest.java, core/src/test/java/brooklyn/entity/basic/ConfigKeysTest.java, utils/common/src/main/java/brooklyn/config/ConfigInheritance.java, utils/common/src/main/java/brooklyn/config/ConfigKey.java
obeyed for entities getConfig AND getAllConfig;
for locations only obeyed for getConfig.
notes in code explain why.
this is applied to a couple of the QuorumCheck config keys to fix an "on-fire" state in one of the stock examples.
=> add support for defining explicit inheritance for config keys

software/nosql/src/main/java/brooklyn/entity/nosql/couchbase/CouchbaseSyncGatewaySshDriver.java
`IS_IN_CLUSTER` [is ONLY set when a server is explicitly added into a cluster](https://github.com/apache/incubator-brooklyn/blob/59208f56a264d85d68ccc51bc9f2acf457dc1107/software/nosql/src/main/java/brooklyn/entity/nosql/couchbase/CouchbaseClusterImpl.java#L461-L462).
The original logic checks for 'IS_IN_CLUSTER'; this means that the sole primary node of a single-node cluster will never be eligible to be used with sync gateway (even though it actually is...!).
We extend the boolean condition to check for this condition.
=> Couchbase SyncGateway should support cluster of ONE node

core/src/main/java/brooklyn/management/internal/AbstractManagementContext.java, software/base/src/main/java/brooklyn/entity/brooklynnode/effector/BrooklynNodeUpgradeEffectorBody.java
Add parameter to choose whether to launch a dry run node or to upgrade directly.
Allow extending classes to customize the effector parameters by overriding a method.
Depends on https://github.com/apache/incubator-brooklyn/pull/413
=> Skip dry run on node upgrade.

core/src/main/java/brooklyn/location/basic/SshMachineLocation.java, core/src/test/java/brooklyn/location/basic/SshMachineLocationIntegrationTest.java, core/src/test/java/brooklyn/util/internal/ssh/SshToolAbstractIntegrationTest.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
This modifies `SshMachineLocation` to propagate certain config keys to flags on `SshTool.execCommand()` and `.execScript()` invocations; the first use of this is to propagate the `scriptDir` config. `JcloudsLocation` is also modified to propagate this configuration. The result is that `scriptDir` can be specified in the configuration for a jclouds-based location, and the value of this property will be passed to every invocation of `SshTool.execScript()`.
The use case for this is to allow Brooklyn to be usable on locations where the VM image mounts `/tmp` with `noexec`.
Also adds some integration tests to verify the correct operation of the `scriptDir` flag.
=> Support scriptDir location config

pom.xml
The quickstart generated project depends on downstream-parent, but it is not yet built. Change modules build order.
=> Fix projects build order

pom.xml
Use `altDeploymentRepository` if alternative repos needed. `brooklyn.deployTo` remains only as a marker to activate source and gpg plugins during build.
=> Remove non-Apache repos

core/src/main/java/brooklyn/entity/basic/ExplicitEffector.java, core/src/main/java/brooklyn/entity/basic/ServiceStateLogic.java, core/src/main/java/brooklyn/event/basic/DependentConfiguration.java, software/nosql/src/main/java/brooklyn/entity/nosql/cassandra/CassandraNodeImpl.java, software/osgi/src/main/java/brooklyn/entity/osgi/karaf/KarafContainerImpl.java
Problems are at places where generics are misused. Usually preceded by compiler warnings.
=> Java 8 compile fixes

core/src/main/java/brooklyn/location/basic/SshMachineLocation.java, core/src/test/java/brooklyn/location/basic/SshMachineLocationIntegrationTest.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
bug introduced in #476
affects all deployments to ssh machines where script dir is not expliclty set, causing NPE
=> fix bug where missing script dir causes null script dir explicitly set in ssh tool

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsMachineNamer.java
After extensive testing it would appear that:
- anything up to 55 chars seems to be fine.  
- 56-58 characters you could jclouds exceptions while provisioning.  
- 59 chars up to around 80 ish you get a provisioned machine with no hostname 
- if you set the chars at higher than 100(ish) you get an error saying that the maximum length had been exceeded.
Someone else please test before merging.
=> Softlayer safe name length

pom.xml, software/network/src/test/java/brooklyn/entity/network/bind/BindDnsServerByonLiveTest.java
Prompted by #503 and bf38d7f7c27e51938e59d8e6ebc75fa7df889f37. We could also prohibit `com.google.api.client` entirely or `..client.util` additionally.
=> Forbid imports from com.google.api.client.repackaged

core/src/main/java/brooklyn/camp/brooklyn/api/AssemblyTemplateSpecInstantiator.java, core/src/main/java/brooklyn/catalog/internal/BasicBrooklynCatalog.java, core/src/test/java/brooklyn/camp/lite/TestAppAssemblyInstantiator.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynAssemblyTemplateInstantiator.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java
* `catalog.createSpec` now passes the symbolicName of the item so resolving to items with the same symbolicName already in the catalogue is prevented (fallback to java types only).
* the recursion check was using the type as is, thus making it possible to recurse into items with the same symbolicName where version is explicitly specified. Explicitly forbid catalog items referencing same symbolicName items, even if with another version.
* stop catalog items whose symbolicName matches the java type they export leaking their bundles to callers.
=> Improve recursion checks for catalog items

docs/_extra/deploying-yaml.md, usage/jsgui/src/main/webapp/assets/css/base.css, usage/jsgui/src/main/webapp/assets/js/util/brooklyn-utils.js, usage/jsgui/src/main/webapp/assets/js/view/entity-config.js, usage/jsgui/src/main/webapp/assets/js/view/entity-sensors.js
applies text shadowing to blur keys that say obvious things like "password" and "credential",
to config table and sensors table. clears up when you click it.
this prevents people looking over your shoulder from seeing things they shouldn't,
but it doesn't block REST access, and if you click on it you can still see it.
(this is a common trick done at AWS & SL, btw.)
a separate feature is to enforce visibility of sensors; this can be done with entitlements on a per-sensor basis
but it might be nice to have an easy entitlements mode where "sensitive" info is not available,
and options on config keys (similar to how i just did it with ConfigInheritance,
in https://github.com/apache/incubator-brooklyn/pull/483) to allow ConfigSensitivity.
an easy way to test is:
curl -v -X POST -H …
=> obfuscate passwords and credentials in the gui (literal "shadow passwords")

core/src/main/java/brooklyn/BrooklynVersion.java, core/src/main/java/brooklyn/util/http/HttpTool.java, core/src/test/java/brooklyn/BrooklynVersionTest.java, usage/cli/src/main/java/brooklyn/cli/AbstractMain.java, usage/cli/src/main/java/brooklyn/cli/Main.java, usage/cli/src/test/java/brooklyn/cli/CliTest.java, usage/cli/src/test/java/brooklyn/cli/CloudExplorerLiveTest.java, usage/launcher/src/main/java/brooklyn/launcher/BrooklynLauncher.java, usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java, usage/launcher/src/test/java/brooklyn/launcher/WebAppRunnerTest.java, usage/rest-server/src/main/java/brooklyn/rest/BrooklynWebConfig.java, usage/rest-server/src/main/java/brooklyn/rest/resources/ServerResource.java, usage/rest-server/src/main/java/brooklyn/rest/security/provider/ExplicitUsersSecurityProvider.java, usage/test-support/src/main/java/brooklyn/test/HttpTestUtils.java
* adds config key for web-console port
* adds CLI for https
* port defaults to 8443+ if no port specified and using https
* default if no CLI options is to show help and an error
* some https test fixes
* discovers and reports Brooklyn OSGi metadata in log, including git SHA1 (and `brooklyn info`)
=> CLI better default, port/https control, and version reporting

utils/common/src/main/java/brooklyn/util/net/Networking.java
Fixes issue [BROOKLYN-130](https://issues.apache.org/jira/browse/BROOKLYN-130). Ensures that the setReuseAddress is called before the port is bound. Removes the attempt to connect to the port before binding it as unnecessary. Corrected off by one error in loop so that port is not incremented beyond MAX_PORT_NUMBER.
=> Release ports acquired when checking available

software/database/pom.xml, software/database/src/main/java/brooklyn/entity/database/crate/CrateNode.java, software/database/src/main/java/brooklyn/entity/database/crate/CrateNodeDriver.java, software/database/src/main/java/brooklyn/entity/database/crate/CrateNodeImpl.java, software/database/src/main/java/brooklyn/entity/database/crate/CrateNodeSshDriver.java, software/database/src/main/resources/brooklyn/entity/database/crate/crate.yaml, software/database/src/test/java/brooklyn/entity/database/crate/CrateNodeIntegrationTest.java
An entity suitable for single-node deployments of Crate. Subsequent work should support clusters as described by the docs: https://crate.io/docs/en/latest/best_practice/multi_node_setup.html.
=> Crate database entity

core/src/main/java/brooklyn/enricher/basic/AbstractTypeTransformingEnricher.java, core/src/main/java/brooklyn/enricher/basic/AddingEnricher.java, core/src/main/java/brooklyn/enricher/basic/Combiner.java, core/src/main/java/brooklyn/enricher/basic/Propagator.java, core/src/main/java/brooklyn/enricher/basic/Transformer.java, core/src/main/java/brooklyn/event/basic/BasicSensorEvent.java, policy/src/main/java/brooklyn/enricher/RollingTimeWindowMeanEnricher.java, policy/src/main/java/brooklyn/enricher/TimeWeightedDeltaEnricher.java, policy/src/main/java/brooklyn/policy/autoscaling/AutoScalerPolicy.java, policy/src/test/java/brooklyn/enricher/RebindEnricherTest.java, policy/src/test/java/brooklyn/enricher/RollingTimeWindowMeanEnricherTest.groovy
before this, autoscaler might scale out on rebind, because the
last total reqs might be 100, if data is v old, current value might be 10000;
a recent timestamp is attached to initial value, meaning it computes 9900 new reqs in a 1s window.
this forces an invalid timestamp for enrichers
better fix would be to store timestamp on sensors themselves
=> fix time-sensitive sensor derivation when rebinding to old sensors

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/brooklyn/entity/rebind/persister/jclouds/JcloudsExpect100ContinueTest.java
The 100 Continue response causes the Java 7,8 http client to misbehave,
more so when used in SSL mode.
Sockets closed by GC break the internal bookkeeping
of HttpUrlConnection, leading to invalid handling of the "HTTP/1.1 100 Continue"
response. Coupled with a bug when using SSL sockets reads will block
indefinitely even though a read timeout is explicitly set.
=> Strip "Expect: 100-Continue" header in Jclouds object store

docs/guide/start/blueprints.md
Emphasis a little the cloud alternative configuration.
=> Blueprint doc remove brackets from alternative configuration.

README.md
Fixed the wrong URL in the README.md file for the quickstart link.
=> fixed the getting started URL

README.md
=> Changed the 'how-to-contrib' URL to point to apache.org

core/src/main/java/brooklyn/entity/rebind/transformer/CompoundTransformer.java, core/src/main/java/brooklyn/entity/rebind/transformer/CompoundTransformerLoader.java, core/src/test/java/brooklyn/entity/rebind/transformer/CompoundTransformerLoaderTest.java, core/src/test/java/brooklyn/entity/rebind/transformer/CompoundTransformerTest.java
* Accept a list of single key-value maps so one file can contain multiple actions with same name
* When renaming a class replace the new name in the class tag, type element, class attribute
=> Improve persistence transformers

usage/rest-server/src/main/java/brooklyn/rest/transform/LocationTransformer.java
Correctly deals with `Maybe` values to avoid spurious warnings like:
````
WARN  Location resolution failed for 'Present[value=localhost]' (will fail shortly):
known resolvers are: [id, named, localhost, byon, single, host, multi, portForwardManager, jclouds, jcloudsByon, pool]
````
=> LocationTransformer: generate correct location spec strings

usage/cli/src/main/java/brooklyn/cli/AbstractMain.java, usage/cli/src/main/java/brooklyn/cli/Main.java, usage/cli/src/test/java/brooklyn/cli/CliTest.java
- Make ASCII art banner customisable
- Make info command customisable
- Make default-info command customisable (i.e. that displayed when no args supplied)
- Remove redundant duplicate Main.cliScriptName, as already declared in AbstractMain
- Adds tests
=> Improve CLI customisability for downstream projects

core/pom.xml, core/src/main/java/brooklyn/entity/rebind/persister/XmlMementoSerializer.java, core/src/main/java/brooklyn/util/xstream/CompilerIndependentOuterClassFieldMapper.java, core/src/main/java/brooklyn/util/xstream/XmlSerializer.java, core/src/test/java/brooklyn/util/xstream/CompilerCompatibilityTest.java, core/src/test/resources/brooklyn/entity/rebind/compiler_compatibility_eclipse.xml, core/src/test/resources/brooklyn/entity/rebind/compiler_compatibility_oracle.xml
The project recently switched from the eclipse-groovy-compiler to the system provided compiler. It turns out that the compilers generate different indexes for the `this$N` fields in non-static inner classes. This results in failures when rebinding to a state generated from a different compiler.
There is one case where there is not enough information in the XML to figure out the new names reliably - when a dynamic class extends another dynamic class and the classes have different this$N field indexes. This is quite rare (we don't have such persisted classes in Brooklyn, though user code might have), in this case the changes will at least log an error, before the rebind fails, with instructions on how to update the fields.
=> Compiler independent persistence

core/src/main/java/brooklyn/location/basic/SshMachineLocation.java
So, for example, the user that the SSH connection is made as can be overridden by providing `PROP_USER` in the flags. Previously it was overwritten by the inclusion of the values in `config().getBag()`.
Happy to be informed that there's already a way to switch the user that the SSH connection is made as.
=> Props given as arguments to SshMachineLocation.connectSsh trump others

core/src/main/java/brooklyn/entity/basic/Entities.java, core/src/main/java/brooklyn/entity/basic/EntityConfigMap.java, core/src/main/java/brooklyn/entity/basic/Sanitizer.java, core/src/main/java/brooklyn/entity/rebind/dto/AbstractMemento.java, core/src/main/java/brooklyn/entity/rebind/dto/BasicEnricherMemento.java, core/src/main/java/brooklyn/entity/rebind/dto/BasicEntityMemento.java, core/src/main/java/brooklyn/entity/rebind/dto/BasicFeedMemento.java, core/src/main/java/brooklyn/entity/rebind/dto/BasicLocationMemento.java, core/src/main/java/brooklyn/entity/rebind/dto/BasicPolicyMemento.java, core/src/main/java/brooklyn/policy/basic/ConfigMapImpl.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsUtil.java
Deprecates the existing method in Entities and updates all references.  Partial fix for BROOKLYN-10
=> Add recursive sanitation and move to own class

core/src/main/java/brooklyn/entity/basic/AbstractEntity.java, core/src/test/java/brooklyn/entity/basic/EntityConfigTest.java
- When return type of config() was changed to BasicConfigurationSupport,
it broke any entity impls that tried to call config().set(...) etc
- Solution is to change BasicConfigurationSupport to be protected
rather than private, and mark as @Beta because we’ll change it
back to private at some point.
=> Fix AbstractEntity.config()

software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java, software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java
Fixes an issue where stopping an entity (with
stopMachineMode of NEVER) and then attempting
to expunge the top level application would
unmanage the entity, but not destroy the VM
=> Destroys machine on expunge, even if stopped

core/src/main/java/brooklyn/entity/basic/DynamicGroupImpl.java, core/src/main/java/brooklyn/management/internal/EntityManagementSupport.java
(since it might unmanage things, esp in the DynamicMultiGroup subclass,
which causes deadlock, as it can't unmanage until management start transition completes)
=> group rescan should be triggered by rebind, but not be in critical rebind path

core/src/main/java/brooklyn/entity/basic/AbstractGroupImpl.java
Check that the `DELEGATE_ENTITY` attribute exists and is set before comparing it with the entity to be removed.
=> Fix NPE in removeMember

software/nosql/src/main/resources/brooklyn/entity/nosql/riak/riak.md
Add license text to make the RAT happy
=> Add Apache 2.0 license text to Riak documentation

core/src/main/java/brooklyn/entity/rebind/persister/FileBasedStoreObjectAccessor.java, core/src/main/java/brooklyn/entity/rebind/persister/PersistenceObjectStore.java, core/src/main/java/brooklyn/entity/rebind/persister/StoreObjectAccessorLocking.java, core/src/test/java/brooklyn/entity/rebind/persister/InMemoryObjectStore.java, core/src/test/java/brooklyn/entity/rebind/persister/ListeningObjectStore.java, locations/jclouds/src/main/java/brooklyn/entity/rebind/persister/jclouds/JcloudsStoreObjectAccessor.java
Convenience for reusing PersistenceObjectStore in slightly different context, in a downstream repo, where we still want to piggie back off the brooklyn.properties way of accessing the object store.
=> Adds PersistenceObjectStore.StoreObjectAccessor.getBytes

core/src/main/java/brooklyn/entity/basic/Entities.java, core/src/main/java/brooklyn/management/internal/LocalEntityManager.java, core/src/main/java/brooklyn/management/internal/LocalUsageManager.java, core/src/main/java/brooklyn/management/internal/NonDeploymentUsageManager.java, core/src/main/java/brooklyn/management/internal/UsageListener.java, core/src/main/java/brooklyn/management/internal/UsageManager.java, software/base/src/test/java/brooklyn/management/usage/ApplicationUsageTrackingTest.java, software/base/src/test/java/brooklyn/management/usage/LocationUsageTrackingTest.java, software/base/src/test/java/brooklyn/management/usage/RecordingLegacyUsageListener.java, software/base/src/test/java/brooklyn/management/usage/UsageListenerTest.java
- Deprecates old interface
- Adds new UsageListener interface that is more flexible and more backwards compatible.
- Marks new interface as @Beta
- Adds tests for new UsageListener, and refactors old tests for old-style UsageListener.
- Adds Entities.proxy(Entity)
=> UsageListener: improve API

software/base/src/main/java/brooklyn/entity/service/EntityLaunchListener.java, software/base/src/main/java/brooklyn/entity/service/InitdServiceInstaller.java, software/base/src/main/java/brooklyn/entity/service/SystemServiceEnricher.java, software/base/src/main/java/brooklyn/entity/service/SystemServiceInstaller.java, software/base/src/main/java/brooklyn/entity/service/SystemServiceInstallerFactory.java, software/base/src/main/resources/brooklyn/entity/service/service.sh, software/base/src/test/java/brooklyn/entity/service/SystemServiceEnricherTest.java
Installs the entity being enriched as a system service. Extracts the launch script from the start effector, saves it and calls it from the service script.
The functionality is wrapped in an enricher so that existing entities can be updated to work as services, but long term it makes sense to move it to the SoftwareProcess entity with INSTALL_AS_SYSTEM_SERVICE={true,false,auto}  where  auto is "true_unless_localhost" configuration.
=> System Service enricher

software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeDriver.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeImpl.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
This is the initial pull request for supporting riak bucket types in brooklyn.
http://docs.basho.com/riak/latest/dev/advanced/bucket-types/
Bucket types are more used for dynamic configurations, for example changing easily properties of a running cluster.
Riak supports adding, updating and deleting bucket types.
I added an effector which creates a bucket type.
I still can not figure out how can we add some monitoring /sensors/ to those bucket types?
=> Riak - Create Bucket type effector

software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
On CentOS 6 and Redhat 6 installing needs to be done with `yum install -y riak-2.0.5` instead of `riak-2.0.5-1 ` which is written on the packagecloud website.
All tests from RiakNodeEc2LiveTest are passing
=> Riak - Fix installation from packagecloud.io on CentOS 6

usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynAssemblyTemplateInstantiator.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/service/BrooklynServiceTypeResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/service/CatalogServiceTypeResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/service/ChefServiceTypeResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/service/JavaServiceTypeResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/service/ServiceTypeResolver.java, usage/camp/src/main/resources/META-INF/services/io.brooklyn.camp.brooklyn.spi.creation.service.ServiceTypeResolver
Adds a `ServiceLoader` plugin capability for parsing the `serviceType: xxx:yyy` part of the YAML blueprint. Includes `brooklyn:`, `java:`, `catalog:` and `chef:` implementations. This will be useful for a `docker:` service type prefix in Clocker.
This is based on my comment on #436 and @neykov's suggestions there.
=> Parse service types in YAML using pluggable resolver impls

core/src/main/java/brooklyn/util/config/ConfigBag.java, core/src/test/java/brooklyn/util/config/ConfigBagTest.java
`ConfigBag` has not been thread-safe, but we have been accessing it from multiple threads.  This can cause `ConcurrentModificationException` to be thrown in many places.
Such a higher-level shared class should be thread-safe, and this makes it so by synchronizing on the `ConfigBag` class appropriately.  As we do not have iterators here it was pretty straightforward.  (You get a copy of the map to iterate -- that has always been the case.)
=> make ConfigBag thread-safe

core/src/test/java/brooklyn/entity/rebind/RebindCatalogItemTest.java, core/src/test/java/brooklyn/entity/rebind/RebindTestFixture.java, usage/rest-api/src/main/java/brooklyn/rest/api/CatalogApi.java, usage/rest-api/src/main/java/brooklyn/rest/api/LocationApi.java, usage/rest-api/src/main/java/brooklyn/rest/domain/CatalogLocationSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/LocationConfigSummary.java, usage/rest-server/src/main/java/brooklyn/rest/resources/CatalogResource.java, usage/rest-server/src/main/java/brooklyn/rest/resources/LocationResource.java, usage/rest-server/src/main/java/brooklyn/rest/transform/CatalogTransformer.java, usage/rest-server/src/test/java/brooklyn/rest/resources/ApiDocResourceTest.java, usage/rest-server/src/test/java/brooklyn/rest/resources/CatalogResourceTest.java, usage/rest-server/src/test/java/brooklyn/rest/resources/LocationResourceTest.java
- On REST api (LocationResource.delete), when location is deleted
then delete from catalog as well as from LocationRegistry.
(Otherwise on rebind it will come back again!)
- Adds LocationApi.delete(symbolicName, version);
Previously just had delete(id))
- Adds to CatalogApi:
- deletePolicy
- deleteLocation
- listLocations
- Change CatalogApi.listEntities return type to List<CatalogEntitySummary>
instead of List<CatalogItemSummary>
- Cleanup LocationApi: deprecated methods to do with definitions,
preferring CatalogApi usage.
- Adds CatalogLocationSummary and LocationConfigSummary
=> Fix delete location from catalog

usage/rest-api/src/main/java/brooklyn/rest/domain/AccessSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/ApiError.java, usage/rest-api/src/main/java/brooklyn/rest/domain/ApplicationSpec.java, usage/rest-api/src/main/java/brooklyn/rest/domain/ApplicationSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/CatalogEntitySummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/CatalogItemSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/CatalogPolicySummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/ConfigSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/EffectorSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/EntityConfigSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/EntitySpec.java, usage/rest-api/src/main/java/brooklyn/rest/domain/EntitySummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/HighAvailabilitySummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/LinkWithMetadata.java, usage/rest-api/src/main/java/brooklyn/rest/domain/LocationSpec.java, usage/rest-api/src/main/java/brooklyn/rest/domain/LocationSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/PolicyConfigSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/PolicySummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/ScriptExecutionSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/SensorSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/TaskSummary.java, usage/rest-api/src/main/java/brooklyn/rest/domain/UsageStatistic.java, usage/rest-api/src/main/java/brooklyn/rest/domain/UsageStatistics.java, usage/rest-api/src/main/java/brooklyn/rest/domain/VersionSummary.java
- Makes everything in brooklyn.rest.domain.* serialisable
- Useful for users of brooklyn.rest.client.BrooklynApi, where
they use these Java objects. Serialisable is not necessary,
but for subsequent usage (e.g. in a mule flow) then it is
useful if they are.
See related PR #583 which has already been merged.
=> REST api domain objects Serializable

software/webapp/src/main/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterImpl.java, software/webapp/src/test/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterIntegrationTest.java
- Was previously a cluster of AS7 nodes; now Tomcat
- The reasons are:
- Tomcat is a popular Apache project; Brooklyn is also in Apache
- AS7 doesn’t support Java 8
=> Switch to Tomcat for ControlledDynamicWebAppCluster

software/webapp/src/main/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterImpl.java, software/webapp/src/test/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterIntegrationTest.java
Advertises http and https ports to parent level application enabling them to be forwarded (for example).
=> propogates http/https ports to ControlledDynamicWebAppCluster entity

docs/README.md, docs/guide/index.md, docs/guide/ops/locations/index.md
* Fixed broken links
* Added download link for improved ease of navigation
* Added passwordless `sudo` requirement to deploying on `localhost`
=> Fixes to Brooklyn site documentation

examples/global-web-fabric/pom.xml
Was depending on brooklyn-all’s with-dependencies, but that has
been deleted. Instead just depend on brooklyn-all.
=> Fix global-web-fabric pom

usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java, usage/launcher/src/test/java/brooklyn/launcher/BrooklynWebServerTest.java
Even though the property is named url it supported local files only.
=> Support URLs in brooklyn.webconsole.security.keystore.url property

locations/jclouds/src/main/java/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationCustomizer.java, locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationTest.java
useful when the customizer is e.g. setting up then clearing external setup, e.g. DNS
=> jclouds location customizer supports pre-release and post-release callback

software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java
During entity startup treat isRunning exceptions as temporary failures and wait until timeout, don't propagate them on the spot. Could be caused by a temporary problem, for example connectivity issues.
=> Don't fail on startup in case of an isRunning exception

pom.xml, usage/downstream-parent/pom.xml
Previously caused an issue if an external project inherits from brooklyn-downstream-parent and depends on brooklyn-rest-client, as these had conflicting jersey.version properties.
First commit reorganises version properties in root pom.xml to make it easier to compare with brooklyn-downstream-parent pom.xml, but does not *change* any versions.
Second commit updates brooklyn-downstream-parent pom.xml with the same versions as the root pom.xml.
=> Fix version conflicts in brooklyn-downstream-parent

core/src/main/java/brooklyn/entity/drivers/ReflectiveEntityDriverFactory.java, core/src/main/java/brooklyn/location/paas/PaasLocation.java, core/src/test/java/brooklyn/entity/drivers/ReflectiveEntityDriverFactoryTest.java, core/src/test/java/brooklyn/location/basic/PaasLocationTest.java, core/src/test/java/brooklyn/test/location/TestPaasLocation.java
An initial support for PaaS locations is provided by adding a new inference rule to [ReflectiveEntityDriverFactory](https://github.com/mbarrientos/incubator-brooklyn/blob/f32fa3cff2174dae18758533e51bddb482eef2c2/core/src/main/java/brooklyn/entity/drivers/ReflectiveEntityDriverFactory.java). The new location [PaasLocation](https://github.com/apache/incubator-brooklyn/blob/f32fa3cff2174dae18758533e51bddb482eef2c2/core/src/main/java/brooklyn/location/paas/PaasLocation.java) is not based on SSH access and is not supposed to be provisioned first (even though it might be the case for some PaaS provider). 
Note that this is part of an ongoing work for integrating PaaS providers, like CloudFoundry, as a Brooklyn Location, which process can be tracked …
=> Add initial support for PaaS locations

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationConfig.java
New `setup.scripts` config which accepts an array of scripts to execute on the node.
=> Support multiple setup scripts in location config

docs/_config.yml, docs/guide/ops/catalog/index.md
tilde is more portable, but apart from that kramdown is more widely used,
and it permits mixing html which we do on the brooklyn landing page
(with redcarpet that didn't render right)
=> switch docs to kramdown and replace triple backticks with triple tilde

utils/common/src/main/java/brooklyn/util/exceptions/Exceptions.java, utils/common/src/main/java/brooklyn/util/text/Strings.java, utils/common/src/test/java/brooklyn/util/text/StringsTest.java
Prompted by the chance observation in VisualVM that way too much CPU time was spent in `Strings.removeFromStart/End ` via `Exceptions.stripBoringPrefixes` and `PropagatedRuntimeException`. Please check a with careful eye.
For more on the time complexity of `String.substring` see http://stackoverflow.com/questions/4679746/time-complexity-of-javas-substring and http://stackoverflow.com/questions/16123446/java-7-string-substring-complexity.
=> brooklyn.util.text.Strings adjustments

pom.xml, software/webapp/src/main/resources/brooklyn/entity/proxy/nginx/server.conf, software/webapp/src/main/resources/brooklyn/entity/webapp/tomcat/server.xml, usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java, usage/launcher/src/test/java/brooklyn/launcher/BrooklynWebServerTest.java, usage/rest-server/src/main/java/brooklyn/rest/BrooklynWebConfig.java
Default config uses weak/compromised ciphers. Followed recommendations from https://wiki.mozilla.org/Security/Server_Side_TLS.
Upgrade of Jetty was needed for the support of white-listing (previous version supported black lists only).
=> White list strong TLS ciphers

software/base/src/main/java/brooklyn/entity/basic/SoftwareProcess.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java, software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityRebindTest.java
Don't create the driver only when `SERVICE_STATE_EXPECTED=ON_FIRE` - the entity is considered permanently failed in this state. When only `SERVICE_STATE_ACTUAL=ON_FIRE` we still should be able to rebind successfully - failure was set by attached enrichers.
=> Initialize entity driver on rebind when on-fire

core/src/main/java/brooklyn/enricher/Enrichers.java
Keep anonymous classes order for rebind backwards compatibility. `computing` present in persistence files but not used.
=> Rebind backwards compatibility

software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
- Basho pulled out 2.1.0, reverted default version to 2.0.5
- packagecloud url was changed
=> Riak bugfix

software/webapp/src/main/java/brooklyn/entity/proxy/nginx/NginxController.java, software/webapp/src/main/java/brooklyn/entity/proxy/nginx/NginxSshDriver.java
* pcre too old and version no longer hosted at official url, updated to currently installed version by brew (as tar download only used on OS X)
* sticky module moved development to bitbucket
Sticky module's archive untars to a different folder than the name of the download, updated the ssh driver to force a subfolder name.
Sticky module (any version) doesn't currently compile with nginx 1.8.0 on OS X. See https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/issue/16/can-not-compile-on-macosx-yosemite. Added a temporary workaround until a fix is released.
=> Upgrade nginx addons

software/webapp/src/main/java/brooklyn/entity/webapp/jetty/Jetty6Server.java
Codehaus seems to be terminating its services (http://www.codehaus.org/termination-410.html) and not hosting/proxying distributions anymore.
=> Replaced Jetty6Server download url.

utils/common/src/main/java/brooklyn/util/net/Networking.java, utils/common/src/test/java/brooklyn/util/net/NetworkingUtilsTest.java
The fix
----------
If the free port check fails for a specific interface, do an additional check if able to bind to an OS picked port on the same IP. If it fails, then there's something wrong with the interface, not just a port already bound error.
Chasing the problem
-----------------
Used https://github.com/apache/incubator-brooklyn/pull/657 as a test bed to figure out what could be wrong when the error occurs. After lost of rebuilds (sorry if you get the jenkins emails) got lucky and hit a case wherre `isPortAvailable` [was failing [1]](https://builds.apache.org/job/incubator-brooklyn-pull-requests/1238/console):
```
java.net.SocketException: No such device
at java.net.PlainSocketImpl.socketBind(Native Method) ~[na:1.6.0_45]
```
when trying to bind to IP …
=> Fix for the "unable to find a free port" Jenkins error

usage/cli/src/main/java/brooklyn/cli/Main.java, usage/launcher/src/main/java/brooklyn/launcher/BrooklynLauncher.java
* Add an option exitAndLeaveAppsRunningAfterStarting to exit the process once the --app entity is up and running
* Force a persist after launching is complete so that the app persistence is guaranteed before exiting
* Pull the startup complete notification before starting the --app entity so that the progress can be monitored in the console.
=> Startup option to exit once the app is deployed and running

core/src/main/java/brooklyn/util/flags/TypeCoercions.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationResolverTest.java
including notes on inheriting, confirming that sets/maps are NOT merged when coming from properties
=> add coercion from string to set, and test location config set/map

usage/launcher/src/test/java/brooklyn/launcher/BrooklynWebServerTest.java
Fix transformation of URL to file path - a good example why one shouldn't use string operations when converting between file path and URL.
Sample failure - https://builds.apache.org/job/incubator-brooklyn-pull-requests/1267/console
```
erifyHttps(brooklyn.launcher.BrooklynWebServerTest)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Unable to access URL brooklyn.webconsole.security.keystore.url: /home/jenkins/jenkins-slave/workspace/incubator-brooklyn-pull-requests%402/usage/launcher/target/test-classes/server.ks
at brooklyn.util.ResourceUtils.getResourceFromUrl(ResourceUtils.java:287)
at brooklyn.util.ResourceUtils.checkUrlExists(ResourceUtils.java:484)
at brooklyn.launcher.BrooklynWebServer.getLocalKeyStorePath(BrooklynWebServer.java:515)
at …
```
=> Fix Jenkins build error - "Unable to access URL brooklyn.webconsole.security.keystore.url"

pom.xml
Fixes test errors when building with Java 6
```
java.lang.NoClassDefFoundError: Could not initialize class freemarker.template.Configuration
```
See http://sourceforge.net/p/freemarker/bugs/394/, https://github.com/freemarker/freemarker/commit/1bc3291c98f8fe80fa211b880366f2bba90f7187
=> Upgrade freemarker, latest version fixes Jython loading errors

pom.xml, software/base/src/main/java/brooklyn/entity/basic/AbstractSoftwareProcessDriver.java
Lots of unit tests assume that no ssh connection will be established when testing localhost entities. The addition of `copy-pre-install-resources` breaks the tests if local ssh is not configured properly. Create install dir only if there are resources to copy (and therefore the test expects it will try to ssh).
=> Don't create install dir in copy-pre-install-resources unless needed

locations/jclouds/src/main/java/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
Clocker has more than one `JcloudsLocation` so the check for exceptions is skipped sometimes, becasue the guard is a static variable shared by all instances. This gives unhelpful error messages occasionally, particularly in the presence of network failures raising `IOException`s.
=> Remove shared statics causing issues in Clocker

software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/main/java/brooklyn/entity/brooklynnode/EntityHttpClient.java, software/base/src/main/java/brooklyn/entity/brooklynnode/EntityHttpClientImpl.java, software/base/src/test/java/brooklyn/entity/brooklynnode/CallbackEntityHttpClient.java
* Fail on non-{2xx, 403} response received
* Fail on BrooklynNode failure
=> Don't spin BrooklynEntityMirror forever on failure

usage/scripts/change-version.sh
Previously the script changed versions in the whole file, regardless of version tags.
=> Change version only on the line following the version tag

core/src/main/java/brooklyn/util/flags/TypeCoercions.java, core/src/test/java/brooklyn/util/internal/TypeCoercionsTest.java
Added two type coercions to class brooklyn.util.flags.TypeCoercions in brooklyn-core:
- String -> java.math.BigDecimal
- String -> java.math.BigInteger
Also added a corresponding test case to TypeCoercionsTest.
=> added type coercions for String to BigDecimal and BigInteger

usage/rest-server/src/main/java/brooklyn/rest/security/PasswordHasher.java, usage/rest-server/src/test/java/brooklyn/rest/security/PasswordHasherTest.java
Using `ByteBuffer.array()` to convert a salted password to its constituent bytes frequently results in an indeterminate number of spurious bytes to be included, due to the fact that the buffer's raw backing array is usually larger than the space consumed just by the values written to it. This causes Brooklyn-generated hashes to deviate from the expected `sha256(salt + password)` values.
Even though Brooklyn itself can generate internally-consistent hashes, it is desirable for the algorithm to be sufficiently predictable to permit generation by simple external mechanisms, for example:
````
echo -n "saltpassword" | openssl dgst -sha256
echo -n "saltpassword" | sha256sum
echo -n "saltpassword" | shasum -a 256
````
=> Tweak PasswordHasher to avoid potentially misleading use of ByteBuffer.array()

core/src/main/java/brooklyn/entity/basic/BrooklynConfigKeys.java, locations/jclouds/src/test/java/brooklyn/location/jclouds/BailOutJcloudsLocation.java, locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationTest.java, software/base/pom.xml, software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java, software/base/src/test/java/brooklyn/entity/software/MachineLifecycleEffectorTasksTest.java
First commit is boring - it just simplifies `JcloudsLocationTest`.
Second commit adds `BrooklynConfigKeys.PROVISION_LATCH`, to block provisioning of locations until some criteria is met.
=> Provision latch

docs/guide/yaml/index.md
Adds link to https://github.com/brooklyncentral/blueprint-library from http://brooklyn.incubator.apache.org/v/latest/yaml/index.html
=> Add link to GitHub blueprint library

examples/webapps/hello-world-sql/pom.xml, pom.xml, software/messaging/pom.xml, software/nosql/pom.xml, usage/camp/pom.xml
Also check if transitive dependencies' versions match during build - `dependencyConvergence` rule in the enforcer plugin.
=> Set explicit versions for conflicting transitive dependencies

software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeImpl.java, software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
Riak has a specific requirement for the number of the allowed open files. It is described at http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/.
Riak generates a warning message if the limit is bellow 65536.
```
Starting riak: !!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
```
This PR provides configuration parameter for the number of the open files. The number of open files will default to the recommended value (65536) in case provided value is less than it.
=> Riak uses ulimit configuration recommended in Basho's docs

usage/rest-api/src/main/java/brooklyn/rest/api/EntityConfigApi.java, usage/rest-client/pom.xml, usage/rest-client/src/main/java/brooklyn/rest/client/BrooklynApi.java, usage/rest-client/src/main/java/brooklyn/util/http/BuiltResponsePreservingError.java
Previously the Response was read into a String, which makes it difficult
to convert back into the domain object.
=> Determine type of entity in rest response from api annotation

software/webapp/src/test/java/brooklyn/entity/webapp/jboss/JBoss6ServerNonInheritingIntegrationTest.java
Remove unnecessary HOSTNAME vs ROOT_URL comparison
=> Fix JBoss6Server Integration Test

core/src/test/java/brooklyn/event/feed/http/HttpFeedTest.java, software/base/src/test/java/brooklyn/entity/basic/lifecycle/StartStopSshDriverTest.java
Functionality covered with next test (without it being integration). Turns out IP 0.0.0.0 points to localhost ports. Ad blockers should reconsider using it :).
Also use port which is known to not be bound, instead of hard coding.
=> Remove redundant (and failing) test

usage/jsgui/src/main/webapp/assets/css/base.css, usage/jsgui/src/main/webapp/assets/js/util/brooklyn-utils.js, usage/jsgui/src/main/webapp/assets/js/view/application-add-wizard.js, usage/jsgui/src/main/webapp/assets/js/view/entity-config.js, usage/jsgui/src/main/webapp/assets/js/view/entity-sensors.js, usage/jsgui/src/main/webapp/assets/tpl/apps/config-name.html, usage/jsgui/src/main/webapp/assets/tpl/apps/sensor-name.html
* config+sensors tooltip renders nicely
* catalog items listed in accordion view don't wrap
* yaml preview window focuses at the top not the bottom (for long blueprints)
The second one needs tested on windows to ensure scrollbars don't clutter.
You can test 2 and 3 with:
```
brooklyn.catalog:
items:
- id: foo-bar-baz-foo-bar-baz-foo-bar-baz-foo-bar-baz-foo-bar-baz-foo-bar-baz-foo-bar-baz_boo
itemType: template
item:
location: localhost
services:
- type:  brooklyn.entity.basic.BasicEntity
brooklyn.config:
x:
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
blah
```
=> Jsgui tweaks

locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, utils/common/src/main/java/brooklyn/util/ssh/IptablesCommands.java, utils/common/src/test/java/brooklyn/util/ssh/IptablesCommandsFirewalldTest.java
Implemented to retain full backwards compatibility before the release
- Adding preliminary support for firewalld
- Starting/stopping/restrting of firewalld service
- Adding rules via firewalld's direct interface
- Tests
=> BROOKLYN-137 stopIptables and openIptables don't work on CentOS7

core/src/main/java/brooklyn/catalog/internal/BasicBrooklynCatalog.java, usage/jsgui/src/main/webapp/assets/js/model/catalog-item-summary.js, usage/jsgui/src/main/webapp/assets/js/model/location.js, usage/jsgui/src/main/webapp/assets/js/view/catalog.js, usage/jsgui/src/main/webapp/assets/tpl/catalog/details-entity.html, usage/jsgui/src/main/webapp/assets/tpl/catalog/details-generic.html, usage/jsgui/src/main/webapp/assets/tpl/catalog/details-location.html, usage/rest-api/src/main/java/brooklyn/rest/api/CatalogApi.java, usage/rest-server/src/main/java/brooklyn/rest/resources/CatalogResource.java, usage/rest-server/src/main/java/brooklyn/rest/resources/LocationResource.java, usage/rest-server/src/test/java/brooklyn/rest/resources/ApiDocResourceTest.java
there was (is) confusion between catalog name and location displayName and a named location.
it deserves a major sort-out, i think treating location defs as catalog items and location instances as entities;
and only using the catalog api, not a dedicated locations api (or if there is, it delegates to catalog),
also removing all the LocationManager blah.
but until then we needed something which avoided confusion where catalog item names for locations
aren't rendered, and magic display names from location-metadata were being showed so it looked
like nothing was being added, though the location worked.
for locations, a catalog item name now does nothing, but the location's name (i.e. human-readable ID aka catalog item ID, not the display name)
is shown in the catalog accordion list (the …
=> clean up how locations are rendered in the js gui, and expand "delete"

core/src/test/java/brooklyn/entity/rebind/persister/XmlMementoSerializerTest.java, usage/camp/pom.xml, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/catalog/AbstractCatalogXmlTest.java, usage/dist/pom.xml
A couple of small issues which would nevertheless cause a release built on a clean build machine to fail.
=> Fixes for release blockers

core/src/main/java/brooklyn/util/flags/MethodCoercions.java, core/src/test/java/brooklyn/util/flags/MethodCoercionsTest.java, docs/guide/ops/locations/index.md, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
Follow on for PR #639; that PR has not been merged, but it's only commit snuck into another PR and has actually been merged. The intention of this PR is to address the review comments.
Resolves the ambiguity around single parameters of type list. Extracts the bulk of the code into a new standalone class and adds tests. Adds documentation.
Tested with this blueprint:
```yaml
location: AWS_eu-west-1
services:
- type: brooklyn.entity.basic.EmptySoftwareProcess
provisioningProperties:
templateOptions:
subnetId: subnet-041c8373
securityGroupIds: ['sg-4db68928']
mapNewVolumeToDeviceName: ["/dev/sda1", 100, true]
```
...and verified that all three parameters (each of which exercise a different code path) had been applied.
=> Clarify operation of `templateOptions` config key

docs/guide/misc/release-notes.md
Updates release notes for the pending 0.7.0 release.
Should not be merged before https://github.com/apache/incubator-brooklyn/pull/687 (Tweak PasswordHasher) is fully resolved.
=> 0.7.0 release notes

core/src/test/java/brooklyn/test/TestHttpRequestHandler.java, core/src/test/java/brooklyn/test/TestHttpServer.java, core/src/test/java/brooklyn/util/ResourceUtilsHttpTest.java, policy/src/test/java/brooklyn/policy/autoscaling/AutoScalerPolicyMetricTest.java, software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/test/java/brooklyn/entity/brooklynnode/BrooklynNodeIntegrationTest.java, software/base/src/test/java/brooklyn/entity/software/http/HttpRequestSensorTest.java, usage/rest-server/src/test/java/brooklyn/rest/resources/CatalogResetTest.java
* Don't unmanage `BrooklynNode` until the STOP effector and all parent entity tasks complete. Prevents `CancellationException: null` error when the STOP effector is called from another effector (i.e. `STOP_NODE_AND_KILL_APPS`)
* AutoScaler now has a default min of 1 member
* Wait for all apps to be running before continuing tests in `BrooklynNodeIntegrationTest` (not just managed)
* Don't use remote services when a local one will do, avoids quota exceeded failures
=> More integration test fixes

software/base/src/main/java/brooklyn/entity/basic/SameServerDriverLifecycleEffectorTasks.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java, software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java
The following YAML was failing to open the port (8080 or 9090) in the AWS security group
```
location: aws-ec2:eu-west-1
services:
- type: brooklyn.entity.webapp.jboss.JBoss7Server
brooklyn.config:
http.port: 9090+
```
=> Fixes issue where port was not being opened if port range was overridden

core/src/main/java/brooklyn/location/basic/ByonLocationResolver.java, core/src/main/java/brooklyn/location/basic/FixedListMachineProvisioningLocation.java, core/src/main/java/brooklyn/location/basic/SshMachineLocation.java, core/src/main/java/brooklyn/location/basic/WinRmMachineLocation.java, core/src/test/java/brooklyn/location/basic/ByonLocationResolverTest.java, core/src/test/java/brooklyn/location/basic/FixedListMachineProvisioningLocationTest.java, core/src/test/java/brooklyn/location/basic/SshMachineLocationTest.java, docs/guide/ops/locations/index.md, software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java, software/base/src/test/java/brooklyn/location/basic/WinRmMachineLocationTest.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlLocationResolver.java, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java, utils/common/src/main/java/brooklyn/util/collections/CollectionFunctionals.java, utils/common/src/main/java/brooklyn/util/net/UserAndHostAndPort.java, utils/common/src/test/java/brooklyn/util/collections/CollectionFunctionalsTest.java
Allows a BYON location to have more complex configuration (e.g. each machine having its own separate map of config), including in YAML.
Also supports a MACHINE_CHOOSER config. This can be used to customize the choice of which available machine should be returned, when obtain() is called.
The motivation is to make BYON more useful for multi-VM deployments, where you want to pick particular machines for particular software components.
=> Feature: byon customization

usage/rest-client/src/main/java/brooklyn/util/http/BuiltResponsePreservingError.java
This code attempted to call non-standard extensions on the `javax.ws.rs.core.Response` class. This change does the appropriate `instanceof` checks to ensure that no non-standard methods are called if
we have a plain old Response object.
=> BROOKLYN-154: Don't call methods that might not be there

usage/rest-client/pom.xml, usage/rest-client/src/main/java/brooklyn/rest/client/BrooklynApi.java, usage/rest-server/src/main/java/brooklyn/rest/filter/LoggingFilter.java
`BuiltResponsePreservingError` can turn response entities into strings, breaking callers of `BrooklynApi.getEntity`.
=> BrooklynApi.getEntity handles instances of BuiltResponsePreservingError

software/base/src/main/java/brooklyn/entity/basic/SoftwareProcess.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java, software/base/src/test/java/brooklyn/entity/basic/VanillaSoftwareProcessAndChildrenIntegrationTest.java, software/webapp/src/test/java/brooklyn/test/entity/TestJavaWebAppEntity.java, software/webapp/src/test/java/brooklyn/test/entity/TestJavaWebAppEntityImpl.java
Thus it is much easier for subclasses of `SoftwareProcess` to customise which effectors they expose and how those effectors behave.
=> SoftwareProcess exposes LifecycleEffectorTasks implementation as config

core/src/main/java/brooklyn/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/brooklyn/util/task/DynamicSequentialTask.java, core/src/test/java/brooklyn/entity/basic/AttributeMapTest.java, core/src/test/java/brooklyn/entity/effector/EffectorTaskTest.java, core/src/test/java/brooklyn/entity/rebind/RebindFeedTest.java, core/src/test/java/brooklyn/entity/rebind/persister/BrooklynMementoPersisterInMemorySizeIntegrationTest.java, core/src/test/java/brooklyn/util/task/BasicTaskExecutionPerformanceTest.java, software/base/src/test/java/brooklyn/management/usage/ApplicationUsageTrackingTest.java, utils/common/src/main/java/brooklyn/util/time/Time.java
A mix of test fixes
* Lots of concurrency fixes (for unit tests) - it's very easy to bring those out by limiting the process to one CPU and using Windows for it's different thread scheduling behaviour.
* Locale independence - use fixed locale when parsing time values
* Integration test fixes
=> Fix failing tests (concurrency problems and integration tests)

docs/guide/ops/launch.md
This follows a customer issue where the Brooklyn server ran out of disk space as nohup.out was > 3GB
=> Changes launch command to redirect nohup to /dev/null

software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNode.java, software/base/src/main/resources/brooklyn/entity/brooklynnode/brooklyn-node.yaml
Include the more reasonable `brooklynnode.distro.uploadurl` attribute in the `brooklyn-node.yaml` example
=> Update brooklyn-node.yaml example

core/src/main/java/brooklyn/location/basic/LocalhostMachineProvisioningLocation.java, software/nosql/src/main/java/brooklyn/entity/nosql/mongodb/sharding/MongoDBShardClusterImpl.java
Probably resolves problems in local and/or cloud environments.
It seems that ```BrooklynAccessUtils``` is the preferred way to determine Brooklyn's accessible address. Now it uses hostname when used with locations in local or cloud environments. On some occasions it should use subnet_hostname instead of the hostname.
```MongoDBShardedDeploymentIntegrationTest``` demonstrates the scenario.
=> MongoDB fixes

core/src/main/java/brooklyn/util/BrooklynMavenArtifacts.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, usage/qa/pom.xml, usage/qa/src/test/java/brooklyn/qa/brooklynnode/SoftlayerObtainPrivateLiveTest.java
By default Softlayer machines will have a hostname of the form `xxxx.local.brooklyncentral.com` which resolves to a parked domain, not the public IP of the machine. When the machine has privte IP only the hostname was used instead of the private IP which caused a failure. This commit removes the hostname fallback - I don't see a valid reason why it should be included.
=> Don't use hostname when obtaining machines

usage/downstream-parent/pom.xml
In commit 3fb4d9a @andreaturli bumped the httpclient version in the parent pom, but he didn't update the version in `brooklyn-downstream-parent` pom. This was causing dependency convergence errors in downstream projects.
=> Fix httpclient version mismatch in pom

usage/launcher/pom.xml
Also make the ordering more natural - almost all projects depend on `utils`. `all`, `dist`, `qa` are includes-all modules.
The build would use an older version of `jsgui` (not the one being compiled with the project), or fail if none is available because `launcher` was built before `jsgui`.  Since `launcher` has only build time dependency on `jsgui` it's not convenient to include it in the dependencies section because it would have to be excluded manually in every project that depends on `launcher`.
=> Fix build order - launcher has build-time depency on jsgui

camp/camp-base/src/main/java/io/brooklyn/camp/spi/resolve/PdpProcessor.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/BrooklynCampReservedKeys.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityMatcher.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlTypeInstantiator.java, usage/camp/src/main/java/io/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/EntitiesYamlTest.java, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/JavaWebAppsMatchingTest.java, usage/camp/src/test/java/io/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java
* Apply flags on catalog items
* Apply flags for fields declared in the entity implementation (or any of the non-primary interfaces)
Makes flags handling more uniform regardless of the entity type (i.e. interface, catalog item, implementation).
=> More uniform handling of YAML flags

software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeSshDriver.java
The expand folder name changed to `brooklyn-dist-<version>`.
Also check the healthy status instead of the root URL so we know the instance has warmed up and is ready to service requests.
=> Update BrooklynNode default expand folder

software/webapp/src/main/java/brooklyn/entity/webapp/DynamicWebAppClusterImpl.java
This fixes TomcatAutoScalerPolicyTest
Basically the problem is that after making a request to Tomcat, update event for REQUEST_COUNT_PER_NODE is triggered immediately.
This causes Enrichers.average() to have a null value for the requests of the newly created Tomcat Entity.
This leads to average of 2 requests per node which exceeds the allowed metric of 0 to 1 which triggers scaling.
It is discuss-able whether we should apply the fix here, but I think in the general case it is good to include count the null when calculating average enrichers.
=> Count the null values for the average enrichers

usage/jsgui/pom.xml, usage/jsgui/src/main/webapp/assets/js/model/catalog-application.js, usage/jsgui/src/main/webapp/assets/js/view/application-add-wizard.js, usage/jsgui/src/main/webapp/assets/tpl/app-add-wizard/deploy-version-option.html, usage/jsgui/src/main/webapp/assets/tpl/app-add-wizard/deploy.html, usage/jsgui/src/test/javascript/specs/model/catalog-application-spec.js, usage/rest-api/src/test/resources/fixtures/catalog-application-list.json, usage/rest-api/src/test/resources/fixtures/catalog-application.json
This PR adds a versions dropdown on the second step modal, when an application is created from a template. This dropdown is always visible for consistency, even if there is only one version available.
Please note that as I was not sure that the `catalog-item` model could apply to any object returned by the `/v1/catalog/*` endpoints so I created a specific one for the applications only: `catalog-application`. It also makes sense as one backbone model should have only one endpoint.
=> [BROOKLYN-132] Add versions dropdown when creating applications from catalog template

core/src/main/java/brooklyn/entity/basic/Entities.java
Simple utility method to obtain a given entity's `ManagementContext`, hiding the cast to the non-public `EntityInternal` class.
=> Add convenience ManagementContext accessor.

docs/website/documentation/index.md, docs/website/download/index.md, docs/website/meta/versions.md
In response to @aledsage's specific comments in PR #773:
* Documentation landing page refers to the latest version, and links to the versions page for everything else.
* Download page recommends Java 1.7 and footnote explains the position with 1.6 and 1.8.
* Versions page no longer links to any snapshot versions (that information should be restricted to the Developers section).
=> Updates as suggested by Aled in PR #773 comments (and a few other tweaks)

usage/jsgui/src/main/webapp/assets/js/view/entity-config.js, usage/jsgui/src/main/webapp/assets/js/view/entity-sensors.js
Previously `foo&bar` was being copied to the clipboard as `foo&amp;bar`
=> Unescapes sensor and config values before copying to clipboard

software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java, usage/cli/src/main/java/brooklyn/cli/Main.java, usage/cli/src/test/java/brooklyn/cli/CliTest.java, usage/launcher/pom.xml, usage/launcher/src/main/java/brooklyn/launcher/BrooklynLauncher.java, usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java, usage/rest-server/src/main/java/brooklyn/rest/resources/ServerResource.java, usage/rest-server/src/main/java/brooklyn/rest/util/ShutdownHandler.java, usage/rest-server/src/main/java/brooklyn/rest/util/ShutdownHandlerProvider.java, usage/rest-server/src/test/java/brooklyn/rest/BrooklynRestApiLauncher.java, usage/rest-server/src/test/java/brooklyn/rest/resources/ServerResourceTest.java, usage/rest-server/src/test/java/brooklyn/rest/resources/ServerShutdownTest.java, usage/rest-server/src/test/java/brooklyn/rest/testing/BrooklynRestApiTest.java, usage/rest-server/src/test/java/brooklyn/rest/testing/BrooklynRestResourceTest.java, usage/rest-server/src/test/java/brooklyn/rest/util/TestShutdownHandler.java
STOPping an app and then doing a shutdown-and-stop-apps could leak machines because the second stop (from the shutdown) can complete faster as it's not re-releasing the machines, then unmanage the app and cancel the first stop's tasks. Cancelling the tasks will not release the machines properly.
This PR works around the problem in the shutdown code. Double stopping an app will still keep the same behaviour.
=> Don't leak machines on shutdown

core/src/main/java/brooklyn/management/entitlement/BasicEntitlementClassDefinition.java, core/src/main/java/brooklyn/management/entitlement/Entitlements.java, core/src/main/java/brooklyn/management/internal/LocalManagementContext.java, core/src/test/java/brooklyn/management/entitlement/AcmeEntitlementManager.java, core/src/test/java/brooklyn/management/entitlement/AcmeEntitlementManagerTestFixture.java
- Adds toString in various places.
- Entitlements.allOf/anyOf takes Utterable<EntitlementManager>, as well
as the overloaded varargs version.
- Clean up reflectively instantiating global EntitlementManager.
- Use catalog-class-loader
- Allow various constructors, for optionally having ManagementContext
and/or BrooklynProperties
- On “reload brooklyn properties”, recreate EntitlementManager in case
entitlements have changed.
=> Entitlements improvements

usage/rest-server/src/main/java/brooklyn/rest/transform/ApplicationTransformer.java, usage/rest-server/src/test/java/brooklyn/rest/resources/ApplicationResourceTest.java, usage/rest-server/src/test/java/brooklyn/rest/testing/BrooklynRestApiTest.java
Previously, if the app’s status was ON_FIRE, the rest api translated
that into “UNKNOWN”. Now it will report it as “ERROR”.
=> Fix REST api app’s status as ERROR when ON_FIRE

api/src/main/java/brooklyn/location/MachineManagementMixins.java, locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java, software/base/src/main/java/brooklyn/entity/basic/SameServerDriverLifecycleEffectorTasks.java, software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessDriverLifecycleEffectorTasks.java, software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
Locations can indicate that they can suspend machines by implementing a new `SuspendsMachines` interface. 
A use of this is given in `MachineLifecycleEffectorTasks`, which provides a `suspend` effector implementation. Attaching this effector to entities is left to subclasses of MLET.
An interface for locations that can resume machines is also given but unused. I began an implementation but realised that we need to discuss what it means to "resume" a machine. Eventually `JcloudsLocation` should implement `SuspendResumeLocation` rather than `SuspendsMachines`.
=> Support suspending machines

core/src/main/java/brooklyn/entity/basic/AbstractApplication.java
* Delete unused fields mgmt, deployed and brooklynProperties.
* Apply setExpectedState and recordApplicationEvent in tandem.
* Make recordApplicationEvent accessible from subclasses.
=> Tidy AbstractApplication

usage/rest-server/src/main/java/brooklyn/rest/BrooklynWebConfig.java, usage/rest-server/src/main/java/brooklyn/rest/security/provider/LdapSecurityProvider.java
Fix LDAP connection parameter.
I tested it locally If the parameters are not formatted in like this `cn=John Smith,ou=Users,dc=example,dc=com` then it fails to recognize the login format `error code 34 - Incorrect DN given`
@grkvlt @aledsage Can you review it please?
=> Fix LDAP dc parameter

usage/dist/src/test/java/org/apache/brooklyn/cli/BaseCliIntegrationTest.java, usage/dist/src/test/java/org/apache/brooklyn/cli/CliIntegrationTest.java, usage/jsgui/src/test/java/org/apache/brooklyn/rest/jsgui/BrooklynJavascriptGuiLauncher.java, usage/jsgui/src/test/java/org/apache/brooklyn/rest/jsgui/BrooklynJavascriptGuiLauncherTest.java, usage/rest-client/src/main/java/org/apache/brooklyn/rest/client/BrooklynApi.java, usage/rest-client/src/main/java/org/apache/brooklyn/util/http/BuiltResponsePreservingError.java, usage/rest-client/src/test/java/org/apache/brooklyn/rest/client/ApplicationResourceIntegrationTest.java, usage/rest-client/src/test/java/org/apache/brooklyn/rest/client/BrooklynApiRestClientTest.java
Rename more packages to add the org.apache prefix.
I have run mvn clean install (which runs the unit tests). For some reason running mvn test alone fails with the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (copy) on project brooklyn-software-base: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187. -> [Help 1]
Maybe some dependencies were missed?
Please review.
=> Rename base package from brooklyn to org.apache.brooklyn - step 2

usage/launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherRebindCatalogTest.java
Fix test - assume the order on catalog rebind doesn't matter.
I didn't debug the actual rebinding code, but I assume since ids and catalogIds are `Iterable` it doesn't matter.
=> BrooklynLauncherRebindCatalogTest

software/osgi/src/main/java/org/apache/brooklyn/entity/osgi/karaf/KarafContainer.java, software/osgi/src/main/java/org/apache/brooklyn/entity/osgi/karaf/KarafContainerImpl.java, software/osgi/src/main/java/org/apache/brooklyn/entity/osgi/karaf/KarafDriver.java, software/osgi/src/main/java/org/apache/brooklyn/entity/osgi/karaf/KarafSshDriver.java, software/osgi/src/test/java/org/apache/brooklyn/entity/osgi/karaf/KarafContainerEc2LiveTest.java, software/osgi/src/test/java/org/apache/brooklyn/entity/osgi/karaf/KarafContainerTest.java
Refs BROOKLYN-162
All tests that are part of the Integration profile are marked WIP.
I did not run any live tests.
There are 2 more issues for this project:
1. src/test/resources contains a hello-world.jar that is used as test OSGi bundle. Shouldn't this be part of the osgi-test-bundles processed by hadrian?
2. Talking of split packages: the sources also contain the classes org.osgi.jmx.Item and org.osgi.jmx.JmxConstants, each with the following note:
```java
/*
* BROOKLYN NOTE: This is a verbatim copy of the original in org.osgi.enterprise-4.2.0, 
* reproduced here to avoid pulling in the rest of that bundle and its chain of dependencies.
* The only difference is this comment and the suppress warnings.
*/
```
As far as I can see org.osgi.enterprise-4.2.0 has no dependencies, though it …
=> brooklyn-software-osgi: add org.apache package prefix

software/messaging/src/main/java/brooklyn/entity/messaging/rabbit/RabbitSshDriver.java
- rpm -Uvh exits with 1 if it is already installed
- replacepkgs ensures that the package will be properly updated
or replaced if already installed
The proposed fix is needed for compatibility between CentOS and RHEL.
RedHat doesn't have EPEL repo enabled by default, but CentOS has.
=> Adding --replacepkgs parameter to ensure proper epel install

core/src/main/java/org/apache/brooklyn/location/access/BrooklynAccessUtils.java, core/src/test/java/org/apache/brooklyn/location/access/BrooklynAccessUtilsTest.java
- Previously there were no unit tests!
- Previously would not look up PortForwardManager unless machine
implemented SupportsPortForwarding (which broke BYON’s tcpPortMappings)
=> Test + fix BrooklynAccessUtils

usage/dist/src/main/dist/bin/brooklyn.ps1
Adds missing 'lib' segment to library 'patch' and 'dropins' dirs
=> Fix launch classpath on Windows

usage/cli/src/main/resources/brooklyn/default.catalog.bom
=> BROOKLYN-162 - fix type name in default catalog

utils/test-bundles/entities/pom.xml, utils/test-bundles/more-entities-v1/pom.xml, utils/test-bundles/more-entities-v2-evil-twin/pom.xml, utils/test-bundles/more-entities-v2/pom.xml
These cannot be installed into a repository and uploaded to Nexus as they do not use the same version number as Brooklyn. They have been breaking our Jenkins CI builds as Nexus refuses to accept non-SNAPSHOT-versioned artifacts into the snapshot repository. We would also likely encounter versioning conflicts for release, too.
This change sets `maven.install.skip` on the affected modules so they are not installed into the local repository, therefore Jenkins will not attempt to deploy them into the remote repository.
=> Skip Maven install for the OSGi test bundles

utils/test-bundles/entities/pom.xml, utils/test-bundles/more-entities-v1/pom.xml, utils/test-bundles/more-entities-v2-evil-twin/pom.xml, utils/test-bundles/more-entities-v2/pom.xml
Like #851, but uses a different property (that one didn't work).
These cannot be installed into a repository and uploaded to Nexus as they do not use the same version number as Brooklyn. They have been breaking our Jenkins CI builds as Nexus refuses to accept non-SNAPSHOT-versioned artifacts into the snapshot repository. We would also likely encounter versioning conflicts for release, too.
This change sets `maven.deploy.skip` on the affected modules so they are not installed into the local repository, therefore Jenkins will not attempt to deploy them into the remote repository.
=> Skip Maven deploy for the OSGi test bundles

core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java, core/src/main/java/org/apache/brooklyn/core/plan/PlanToSpecFactory.java, core/src/main/java/org/apache/brooklyn/core/plan/PlanToSpecTransformer.java, core/src/test/java/org/apache/brooklyn/core/plan/XmlPlanToSpecTransformer.java, core/src/test/java/org/apache/brooklyn/core/plan/XmlPlanToSpecTransformerTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/TypeCoercionsTest.java, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/api/AssemblyTemplateSpecInstantiator.java, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynAssemblyTemplateInstantiator.java, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampToSpecTransformer.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/test/lite/TestAppAssemblyInstantiator.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java
It's pretty straightforward to write a new plan-to-spec transformer.  This paves the way for TOSCA support, among other things.
I wonder in time about this being bi-directional, i.e. also usable for persisting and rebinding.
/cc @aledsage @neykov
=> Illustration and test for PlanToSpecTransformer, and tidies

docs/guide/java/archetype.md
Updates https://brooklyn.incubator.apache.org/v/0.7.0-SNAPSHOT/java/archetype.html with correct package name in command
Tested on: https://github.com/apache/incubator-brooklyn/releases/tag/apache-brooklyn-0.7.0-incubating
=> Update archetype command with correct package name

api/src/main/java/org/apache/brooklyn/api/location/MachineManagementMixins.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/location/byon/ByonLocationResolver.java, core/src/test/java/org/apache/brooklyn/location/byon/ByonLocationResolverTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationRebindMachineLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationRegisterMachineLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationSuspendResumeMachineLiveTest.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/LocationResource.java
* `JcloudsLocation` implements `SuspendResumeLocation` (rather than just `SuspendsLocations`).
* The various `rebindMachine` methods in `JcloudsLocation` are deprecated in favour of `registerMachine`, which returns a `MachineLocation` rather than a `JcloudsSshMachineLocation`. This means that it can also be used to register Windows-based systems.
=> Resuming locations

core/src/main/java/org/apache/brooklyn/location/byon/ByonLocationResolver.java, core/src/test/java/org/apache/brooklyn/location/byon/ByonLocationResolverTest.java, docs/guide/ops/locations/index.md, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessStreamsTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessAndChildrenIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinrmStreamsLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java
This PR provides stdin, stderr and stdout support to the Windows commands.
Look the commits to see the changes
**Not** ready for review.
It has a Live tests for it and there is an example blueprint for windows byon location which I can remove from the PR if you'd like.
I also changed the config key ByonLocationResolver.OS_FAMILY. Here are my comments on these 
So JcloudsLocationConfig.OS_FAMILY config key is osFamily and for ByonLocationResolver.OS_FAMILY it is osfamily without capital F
I was thinking for fixing it by moving this config key to AbstractLocation. Is it possible that we don't want to include this config to all descendants of AbstractLocation?
=> Winrm commands stdin, stdout, stderr; Commands Live tests

core/src/main/java/org/apache/brooklyn/core/location/cloud/names/BasicCloudMachineNamer.java, core/src/test/java/org/apache/brooklyn/core/location/cloud/CloudMachineNamerTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsMachineNamerTest.java
- timeStamp replaces the previously used randId. 
- timeStamp uses the standard unix timestamp represented
as a 8-char hex string.
- It represents the moment in time when the name is constructed. 
- It gives the possibility to search easily for instances, security
groups, keypairs, etc based on timestamp without complicated
enumeration
=> Adding timestamp to the template options' name

docs/guide/ops/install-on-server.md, docs/guide/start/policies.md, docs/guide/start/running.md
Correct archive name and path for installation. Fix typos.
Bump Java version to 1.7 in install-on-server.md.
Change Brooklyn to Apache Brooklyn in headings and first occurence in the body text.
=> Small edits to documentation.

locations/jclouds/src/main/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicy.java, locations/jclouds/src/test/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicyLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicyTest.java
- Added parameter (BYON_USER_RESET_PASSWORD)
- BYON_USER_RESET_PASSWORD controls when password to be reset
- Whether to reset the password of the BYON login user in case it is
used to create a new one, e.g. via a custom security policy such as
org.apache.brooklyn.policy.jclouds.os.CreateUserPolicy"
=> Fix for BROOKLYN-169 - CreateUserPolicy always resets the password

core/src/main/java/org/apache/brooklyn/enricher/stock/Propagator.java, core/src/test/java/org/apache/brooklyn/enricher/stock/SensorPropagatingEnricherTest.java
=> Changes propagator getDestinationSensor to lookup on sensor name, rather than sensor equality

docs/guide/dev/env/ide/index.md
Remove reference to Java 1.6 (Brooklyn doesn't support this any more) and add a note about "optimize imports" reconfiguration.
=> Update IntelliJ guidelines in developer's guide

utils/common/src/main/java/org/apache/brooklyn/util/repeat/Repeater.java
Easy to do, so why not? Allows it to be passed directly to the `body()` method of a `TaskBuilder` for instance.
=> Make Repeater a Callable

software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlCluster.java, software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlClusterImpl.java, software/database/src/test/java/org/apache/brooklyn/entity/database/mysql/MySqlClusterIntegrationTest.java, software/database/src/test/java/org/apache/brooklyn/entity/database/mysql/MySqlClusterTestHelper.java
`CREATION_SCRIPT_{URL, CONTENT} `was applied to the master node pre-replication-init so there was no way to initialize the slave nodes. Improved by:
* Applying `CREATION_SCRIPT_{URL, CONTENT} ` on all nodes, including slaves pre-replication-init
* Introducing a new `MASTER_CREATION_SCRIPT_{URL, CONTENT} ` config applied on master only post-replication-init
=> Fix MySqlCluster script init

usage/cli/src/main/java/org/apache/brooklyn/cli/AbstractMain.java, usage/cli/src/main/java/org/apache/brooklyn/cli/Main.java, usage/cli/src/test/java/org/apache/brooklyn/cli/CliTest.java, usage/launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java
* CLI accepts `-Da=b -Dc=d ...`
* JS GUI uses a custom cookie ID so as not to conflict with multiple brooklyn sessions or other services (e.g. alien4cloud) coming from the same server
=> Usage goodies

api/src/main/java/org/apache/brooklyn/api/entity/EntityLocal.java, api/src/main/java/org/apache/brooklyn/api/mgmt/SubscriptionContext.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicSubscriptionContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/SubscriptionTracker.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/DeserializingClassRenamesProvider.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/enricher/stock/UpdatingMap.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitySubscriptionTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManagerTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/PolicySubscriptionTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/SubscriptionPerformanceTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java
Various fixes for things encountered (or speculatively encountered for "notifyOfInitialValue"!) when testing upgrade from an old Brooklyn to a new brooklyn.
=> Fix service-not-up-diagnostics, add subscription.notifyOfInitialValue, etc

core/src/main/java/org/apache/brooklyn/enricher/stock/UpdatingMap.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7ServerImpl.java
Previously, serviceUp was never set to true, for two reasons:
1. because connectServiceUpIsRunning was not called, nothing was
unsetting the service-not-up-indicator for SERVICE_PROCESS_IS_RUNNING
2. because the service-not-up-indicator for MANAGEMENT_URL_UP said
suppressDuplicates=true, then it checked if the map was equal to
the “old” map before publishing. But the map was the same object,
and that object had been modified in-place. So the object was
always equal to itself. It therefore never did an emit(), so the
enricher that listened to it to set serviceUp never fired.
Also fix UpdatingMap for if suppressDuplicates=true:
- log.warn to say it should not be set.
- reset config to suppressDuplicates=false
=> Fix jboss service not up

usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java
This will look inside a collection (Set, Map or List) and will resolve the value that uses $brooklyn:*
=> Resolve DSL functions for a configuration key within any collection

docs/guide/start/brooklyn.properties
There were some random characters in a commented line in the file.
=> Remove invalid characters from brooklyn.properties

parent/pom.xml
Fixes failing builds where the compiler is looking for a non existing generated-sources/annotations folder.
=> Update the plexus eclipse compiler to latest stable

software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java
`isRunning` wasn't set for BrooklynNode due to the ssh check being skipped in favour of http check (see https://github.com/apache/incubator-brooklyn/pull/790)
Infer `isRunning` from the `brooklynnode.webconsole.up` value.
=> Fix BrooklynNode isRunning check

software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcess.java
Re-orders the config keys into a sensible order, and adds priority
to the CatalogConfig.
Removes the default from LAUNCH_COMMAND.
Addresses the comments in https://github.com/apache/incubator-brooklyn/pull/927
=> VanillaWindowsProcess CatalogConfig: add priority

core/src/test/java/org/apache/brooklyn/core/test/BrooklynAppLiveTestSupport.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessSshDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessStreamsTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessIntegrationTest.java
Previously, if download and install-cmd were supplied, only the 
download would be executed.
Previously if two VanillaSoftwareProcesses were used on the same
machine where neither had a downloadUrl, it would have skipped the
install of the second (sharing the same install folder).
Previously there was poor test coverage of VanillaSoftwareProcess.
=> Fix VanillaSoftwareProcess install

usage/jsgui/src/main/webapp/assets/css/base.css, usage/jsgui/src/main/webapp/assets/js/model/app-tree.js, usage/jsgui/src/main/webapp/assets/js/view/application-explorer.js, usage/jsgui/src/main/webapp/assets/js/view/application-tree.js, usage/jsgui/src/main/webapp/assets/js/view/entity-summary.js, usage/jsgui/src/main/webapp/assets/tpl/apps/summary.html, usage/jsgui/src/main/webapp/assets/tpl/apps/tree-item.html
* Display group members alongside children.
* Each entity still has one "direct" position in the hierarchy, but may also have several "indirect" references.
* Indirect nodes can be interacted with in-place as normal:
* show details, invoke effectors, expand children, etc.
* Indirect subordinates have a distinct visual style to avoid confusion.
@grkvlt: Would love to know if this plays well with Clocker, which I know makes heavy use of groups.
=> Better group member display

usage/jsgui/src/main/webapp/assets/tpl/app-add-wizard/required-config-entry.html
Attempting to fix:
The enum drop-downs are not supposed to start with ">", and should say "Virtualization" rather than the selected= stuff.
My change reverts a change that sneaked in as part of the commit "[BROOKLYN-162] package rename to org.apache.brooklyn: software/webapp"!
However, when I just ran with it in a downstream project, it seemed not to alter the behaviour at all.
Maybe my javascript was cached or maybe the downstream build actually downloaded the latest snapshot Brooklyn (rather than taking my local build)?!
=> Fix add-app-wizard for enums (WIP)

software/database/src/main/java/org/apache/brooklyn/entity/database/postgresql/PostgreSqlSshDriver.java
- RedHat BYON returns osname as "Red Hat Enterprise Linux", instead of
the expected "rhel"
=> Fix osname check when PostgreSQL is installed on RedHat BYON location

api/src/main/java/org/apache/brooklyn/api/entity/Entity.java, core/src/main/java/org/apache/brooklyn/core/config/BasicConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java, core/src/main/java/org/apache/brooklyn/core/config/ConstraintViolationException.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/location/AbstractLocation.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractConfigurationSupportInternal.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/core/objs/BrooklynObjectInternal.java, core/src/main/java/org/apache/brooklyn/core/objs/BrooklynObjectPredicate.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalPolicyFactory.java, core/src/main/java/org/apache/brooklyn/util/core/ResourcePredicates.java, core/src/main/java/org/apache/brooklyn/util/core/ResourceUtils.java, core/src/test/java/org/apache/brooklyn/core/config/ConfigKeyConstraintTest.java, docs/guide/concepts/configuration-sensor-effectors.md, docs/guide/java/entities.md, usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/AbstractBrooklynRestResource.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, utils/common/src/main/java/org/apache/brooklyn/config/ConfigKey.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/PredicateWithContext.java
Allows constraints to be specified on config keys. 
Constraints are eagerly enforced when entities are first managed and when policies and enrichers are created. At other times they are not enforced. Constraints can only be checked on ConfigKeys that are declared on the object's type hierarchy.
A constraint is a `Predicate<T>`, where `T` is the type of the `ConfigKey` in question. Guava's predicates provide almost all of the obvious use cases. I've written `ResourcePredicates.urlExists()` to use with config keys that represent things like files Brooklyn will load and run through Freemarker. I've verified that this works with resources in bundles. Adding this required a couple of adjustments to `NonDeploymentManagementContext`.
See the tests in `ConfigKeyConstraintTest` for most scenarios …
=> Config constraints

docs/guide/yaml/creating-yaml.md
Amended paragraph in section "The Basic Structure" to clarify reference to the copy icon and to add some apparently missing text.
=> Amend text in creating-yaml.md

software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNode.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeSshDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeIntegrationTest.java
classpath can be a list of
- URLs or file names or directory names as before,
- maps specifying a URL and a filename,
e.g. { "url": "http://...", "filename": "myfile.jar" }
This feature is needed to fix incorrect filename deduction in
situations where the URL does not contain an explicit jar name
Finally, the destination directory has been changed from ./lib to
./lib/dropins
=> Extend brooklynnode.classpath config options

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
Each `DynamicCluster` member entity now has a `cluster.member.id` integer config value representing the order in which it was added to the cluster, starting from 0 and increasing sequentially.
=> Add sequential ID number to each DynamicCluster member

usage/jsgui/src/main/webapp/assets/js/view/application-add-wizard.js
Right now, the app wizard modal pass all additional configurations as `String`. If the entities have configkey with different types, an array of integers for example, Brooklyn will fail right after hitting the `Finish` button because it won't be able to convert `"[]"` as an array.
This will correctly convert string value, entered within the app wizard, into their corresponding Javascript type. For instance:
- `[1,2,3,4]` will be converted as a JS `Array` that contains 1, 2, 3 and 4 integers (`Number` type)
- `{"test": true}` will be converted as a JS `Object` containing the field `test` with the boolean value `true`
- `true` will be converted as a `Boolean`
- `0.123456` will be converted as a `Number`
If the conversion fails, it will fallback to the previous implementation which is taking …
=> Add support for correct configkey conversion from the app wizard UI

docs/guide/ops/locations/index.md
The current Locations page provides information on setting up passwordless SSH
and says that passwordless sudo is required, but does not tell the user how to setup.
=> Add description for configuring passwordless sudo to localhost location.

core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/MongoDBReplicaSetImpl.java
The `NEXT_CLUSTER_MEMBER_ID` attribute was uninitialised, causing an exception in `addNode`.
=> Prevent DynamicCluster NPE when subclasses have not called super.init()

locations/jclouds/src/main/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicy.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java, utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
- Sudo is compiled with --without-secure-path on Suse
- Brooklyn uses sudo with the -E parameter which preserves the
user environment
- CreateUserPolicy needs commands only available on the secure path
locations
=> Fix CreateUserPolicy for SuSe Linux

core/pom.xml, parent/pom.xml, software/webapp/pom.xml
Resolves Eclipse build errors in `XmlPlanToSpecTransformer`. Command-line Maven build was happy, possibly due to later version accidentally getting picked up via transitive dependency.
=> Update ‘xml-apis’ dependency

docs/guide/yaml/custom-entities.md, docs/guide/yaml/example_yaml/vanilla-bash-netcat-w-client.yaml
Set the sensor periods to 1 sec, the default 5 minute sensor period is too long for this example.
=> shortened sensor period in netcat with client yaml example

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/MutableList.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/MutableSet.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/MutableSetTest.java
Fixes BROOKLYN-186 by working around if jclouds gives us the wrong login user, or gives us both a password and ssh key (where only one of them works).
It's a bit messy doing this, but feels like the most robust thing to do.
(The other commit about `MutableSet` is just to make that easier to use in my JcloudsLocation fix, and to improve test coverage while I was at it).
=> BROOKLYN-186 workaround in JcloudsLocation

docs/guide/start/managing.md
Updated Monitoring And Managing Applications document /sensors section - based on feedback from Belfast first contact task.
9. told to 'quickly return to sensors tab' without having left it, redundant wording should be cleaned.
10. make location of webapps reqs per second sensor explicit (there are multiple locations)
15. point user to location of load balancer URL for validation app deployment - also need to say that for Softlayer/Azure/GCE it may show the internal IP in the URI. So one would have to find the public IP of the load-balancer if trying to connect to it.
=> Updated Monitoring And Managing Applications - sensors section

software/base/src/main/java/org/apache/brooklyn/entity/machine/SetHostnameCustomizer.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/SetHostnameCustomizerTest.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java, utils/common/src/test/java/org/apache/brooklyn/util/exceptions/ExceptionsTest.java
Adds support for MACHINE_FILTER, so you can tell it not to run against windows machines etc. Default is only to run against `SshMachineLocation` machines.
Also adds some tests for Exceptions (as I added an extra utility method there, to make my test easier to write).
=> Fix: SetHostnameCustomizer error handling

software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineInitTasks.java
Some changes are applied to openIptables execution:
1. "open iptables" task has sub tasks "insert rules" and "list rules" which show in the activity log.
2. "insert rules" has sub tasks - (1) insert rules, divided on commands batches of 100 rules where each batch is a sub task and shows in the activity log and (2) "save" sub task
Every leaf task has streams stdin, stdout, stderr.
=> Refactoring openIptables execution

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java
Will warn if two AWS security groups not found, but tries to return the single group. Throws `IllegalArgumentException` if zero or more than two.
=> With Clocker microservice only one security group on AWS for customizer

software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlClusterImpl.java
The raw cast erases all generics, forcing the return value to the bound which is `AbstractAggregatorBuilder`. Following method calls get resolved against the inaccessible (protected) `AbstractAggregatorBuilder` which leads to compile errors. This is a problem in Java 8. Java 7 and the Eclipse compiler don't need the additional cast.
=> Fix Java 8 build error

core/pom.xml, docs/guide/dev/env/ide/eclipse.include.md, docs/guide/dev/env/ide/index.md, parent/pom.xml, usage/downstream-parent/pom.xml
The changes allow the project to be imported in vanilla "Eclipse for Java Developers" install without using additional plugins.
Also upgrades the groovy related dependencies to latest release.
=> Ignore Groovy plugin in Eclipse build

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/Osgis.java, karaf/commands/pom.xml, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/Catalog.java, karaf/itest/pom.xml, karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java, karaf/pom.xml
This addresses most of the comments in #962. Also included is a fix the karaf assembly project build, which leads to problems further on with brooklyn-itest.
The current quick-fix is to disable brooklyn-itest, so that the jenkins build won't be a problem for everyone until we manage to integrate it properly.
=> Brooklyn OSGification - step 1 fixes

utils/common/src/test/java/org/apache/brooklyn/util/HttpAssertsTest.java
Later task will be to restructure to avoid sleeps where possible, see conversation at
https://github.com/apache/incubator-brooklyn/pull/994#issuecomment-154074295.
=> Make the HttpAssertsTest an integration test for now.

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultAppIdExternalConfigSupplier.java, core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java, core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultTokenExternalConfigSupplier.java, core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultUserPassExternalConfigSupplier.java, core/src/test/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplierLiveTest.java, docs/guide/ops/externalized-configuration.md, docs/guide/ops/index.md
Adds an implementation of ExternalConfigSupplier for Hashicorp [Vault](https://www.vaultproject.io).
Also provides documentation for the externalized configuration system.
=> Hashicorp Vault external config supplier, plus documentation for external config

core/src/test/java/org/apache/brooklyn/core/entity/EntityAssertsTest.java, utils/common/src/main/java/org/apache/brooklyn/test/http/TestHttpServer.java, utils/common/src/main/java/org/apache/brooklyn/util/http/HttpAsserts.java, utils/common/src/test/java/org/apache/brooklyn/util/HttpAssertsTest.java
@geomacy a few tidies to HttpAssertsTest
i think this should fix the failures we've seen on hosted jenkins, which i think are due to delays cleaning up ports.
however it should remain an integration test except for those which run with no delays (btw i think doing that is low priority -- good integration coverage is sufficient)
=> tidy of HttpAssertsTest

core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, core/src/test/java/org/apache/brooklyn/util/core/internal/TypeCoercionsTest.java
Added coercions to handle cases where a String ConfigKey is being populated from URI/URL typed sensors. For example (where `url` is a `String`, and `main.uri` is a `URI`):
```
url: $brooklyn:component("tomcat").attributeWhenReady("main.uri")
```
*Note*: I can only find Brooklyn entities using either `URI` or `String` to store URLs, have included a `URL` coercion for completeness.
=> added missing URI/URL to String coercions

core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/AppYamlTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ApplicationsYamlTest.java
There's an unexpected side effect presently where pointing to a catalog item and giving a top-level name to the plan will prevent unwrapping. It's surprising to users and even more so because it wasn't the case a few months ago.
For example the following catalog item:
```
brooklyn.catalog:
id: simpleApp
version: 1.0
displayName: Simple App
itemType: template
item:
services:
- type: my-simple-app
```
when started in the Application Wizard and given a name, equivalent to the following plan:
```
name: My App
services:
- type: "simpleApp:1.0"
```
will result in this hierarchy:
```
* My App (BasicApplication)
* Simple App (my-simple-app)
```
I propose that we change the logic such that the root level name will overwrite the child's name, so the hierarchy becomes:
```
* My App (my-simple-app) …
```
=> Unwrap camp plan with parent overriding child displayName

usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampUtils.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java
#1001 & #1007 combined lead to a test failure, when each of them separately would work just fine.
=> Fix master build

core/pom.xml
For some reason the `brooklyn-core` bundle still imports `org.apache.felix.framework`, even if the actual code was moved to `brooklyn-rt-felix` and excluded from `brooklyn-core`'s imports.
This PR addresses this issue.
=> [BROOKLYN-183] Fix karaf package wiring for brooklyn-core

api/src/main/java/org/apache/brooklyn/api/location/Location.java, core/src/main/java/org/apache/brooklyn/core/location/AbstractLocation.java, core/src/main/java/org/apache/brooklyn/core/location/AggregatingMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/core/location/access/PortForwardManagerClient.java, core/src/main/java/org/apache/brooklyn/core/sensor/AttributeMap.java, core/src/main/java/org/apache/brooklyn/entity/stock/EffectorStartableImpl.java, core/src/main/java/org/apache/brooklyn/location/byon/SingleMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/multi/MultiLocation.java, core/src/test/java/org/apache/brooklyn/core/location/AbstractLocationTest.java, core/src/test/java/org/apache/brooklyn/core/location/LocationExtensionsTest.java, core/src/test/java/org/apache/brooklyn/core/location/SimulatedLocation.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindLocationTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicyTest.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPoolLocation.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityRebindTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/StartStopSshDriverTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/core/mgmt/usage/LocationUsageTrackingTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogParametersTest.java, usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/UsageResourceTest.java, utils/common/src/main/java/org/apache/brooklyn/util/JavaGroovyEquivalents.java, utils/common/src/test/java/org/apache/brooklyn/util/maven/MavenArtifactTest.java, utils/common/src/test/java/org/apache/brooklyn/util/ssh/IptablesCommandsTest.java, utils/test-support/src/main/java/org/apache/brooklyn/test/support/TestResourceUnavailableException.java
Deletes `extends Serializable` from location interface, and removes all declared serialVersionUID from location implementations.
Location was not really serialisable anyway - for example it had non-transient references to `ManagementContext`. The declaration of “Serializable” was a throwback to very old days when persistence was imagined to be very different.
Also has some other very minor tidy up (in separate commits).
=> location is not serializable

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessor.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessorWriterTest.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java, utils/common/src/main/java/org/apache/brooklyn/util/io/FileUtil.java, utils/common/src/test/java/org/apache/brooklyn/util/exceptions/ExceptionsTest.java
- Adds Exception.propagate(msg, throwable) so can include info about
the file that could not be created.
- Fix FileUtil.setFilePermissions so that createNewFile creates the
parent directory if necessary.
- HighAvailabilityManager’s polling task: log.err on first exception,
then log.debug for subsequent consecutive exceptions.
=> BROOKLYN-144: avoid err when persisting ha-record

usage/test-framework/README.md, usage/test-framework/pom.xml, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/AbstractTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/BaseTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCase.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCaseImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCase.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCaseImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestEffector.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestEffectorImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensor.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensorImpl.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestEffectorTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSensorTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestEntity.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestEntityImpl.java, usage/test-framework/src/test/resources/test-framework-examples/README.md, usage/test-framework/src/test/resources/test-framework-examples/example-catalog-test.bom, usage/test-framework/src/test/resources/test-framework-examples/example-catalog.bom, usage/test-framework/src/test/resources/test-framework-examples/nginx-test-examples.yml, usage/test-framework/src/test/resources/test-framework-examples/testhttpcall-examples.yml, usage/test-framework/src/test/resources/test-framework-examples/tomcat-test-examples.yml
The `test-framework` was using an incorrect parent pom so the `apache-rat-plugin` did not fail the build
=> Adding missing ASF license headers to test-framework

core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessorWriterTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/AbstractPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/EntityPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/FilePersistencePerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/GroovyYardStickPerformanceTest.groovy, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/JavaYardStickPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/SubscriptionPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/TaskPerformanceTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStorePersistencePerformanceTest.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/FilePersister.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/Histogram.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/MeasurementResultPersister.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceMeasurer.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceTestDescriptor.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceTestResult.java, usage/test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceTestUtils.java
Our performance tests need a much bigger overhaul. However, these changes make them a bit more usable - and makes them record performance results in a local file which is better than nothing.
- Extracts code from AbstractPerformanceTest into PerformanceMeasurer, making it more configurable and usable from more places.
- Adds a default persister to write files to `~/brooklyn-performance/` (while we figure out where to write those to in anger).
=> Improve performance tests

docs/guide/index.md, docs/guide/test/entities.md, docs/guide/test/index.md, usage/test-framework/README.md, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCaseImpl.java
Addressed review comments.
* Changed how ParallelTestCase task is submitted and waited upon. Functionally no change.
* Also added ParallelTestCase documentation to the docs.
* Moved the Test Entities documentation to within the Brooklyn docs guide.
=> ParallelTestCase change and documentation updates

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/RebindExceptionHandler.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicEntityRebindSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindExceptionHandlerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java, docs/guide/ops/persistence/index.md
Add configuration option for skipping invalid config values
=> BROOKLYN-193: Add configuration for skipping invalid configs

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLoginLiveTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java, utils/common/src/test/java/org/apache/brooklyn/util/net/NetworkingUtilsTest.java, utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
(Unrelated to other changes, fixes `NetworkingUtilsTest.testIsPortAvailableReportsTrueWhenPortIsFree`).
Lots of fixes to get the `JcloudsLoginLiveTest` working again.
- registerJcloudsSshMachineLocation: use the userCredentials that are passed into the method, rather than looking up what we expect from the config.  
(Hopefully fixes testSpecifyingPasswordAndSshKeysPrefersKeys).
- Fix waitForSshable to when password supplied on JcloudsLocation config, and using useJcloudsSshInit=false.
- Fix use of DISABLE_ROOT_AND_PASSWORD_SSH: if for root user with password-based login, then explicitly set PasswordAuthentication=yes.  
If root user, then explicitly set PermitRootLogin=true
- Fix getPublicHostnameAws so pass in the credentials (some code-paths will not have configured the credentials in …
=> Fix jclouds sshable

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationSshToolTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, software/base/src/test/java/org/apache/brooklyn/entity/java/JavaOptsTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/EntitySshToolTest.java
When overriding the SshTool implementation to use, allows extra config to be supplied that will be passed to the constructor.
=> Config supplied to SshTool’s constructor

docs/guide/start/concept-quickstart.md, docs/guide/start/index.md, docs/guide/start/running.md, docs/website/index.md
The concepts quickstart is moved to the end of the section and added as an suggested reference to the landing page (which is the Running Brooklyn page again) in order to simplify the flow.
=> Restored getting started guide landing page.

usage/rest-client/pom.xml
Removes a few that are unused, marks `org.eclipse.jetty:jetty-server` as a test dependency and excludes `brooklyn-utils-rest-swagger` (which transitively means Scala is not pulled in). Downstream clients should be much lighter weight (in the order of 10Mb if they package rest-client's dependencies).
=> Review rest-client's dependencies

utils/rest-swagger/src/main/java/org/apache/brooklyn/rest/apidoc/RestApiResourceScanner.java
The swagger changes lead to the following error in eclipse: 
```Cannot cast from MutableSet<Class<capture#4-of ? extends Object>> to MutableSet<Class<?>>```
There's also no need for a MutableSet.
=> Fix eclipse 'Cannot cast' error

usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/BaseTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensorImpl.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestHttpCallTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSensorTest.java, usage/test-framework/src/test/resources/test-framework-examples/example-catalog-test.bom, usage/test-framework/src/test/resources/test-framework-examples/nginx-test-examples.yml, usage/test-framework/src/test/resources/test-framework-examples/testhttpcall-examples.yml, usage/test-framework/src/test/resources/test-framework-examples/tomcat-test-examples.yml
TestFrameworkAssertions is a common class used by [TestSensor,TestHttpCall] instead of each entity having its own assertions
```
assert:
isEqualTo: SomeValue
```
```
assert:
- isEqualTo: SomeValue
```
Currently Supported assertions [isNull,notNull,isEqualTo,equalTo,equals,matches,contains]
Added new config key `applyAssertionTo` possible values [body,status]
```
type: org.apache.brooklyn.test.framework.TestHttpCall
name: Assert 200 OK
url: http://localhost:8081
assert:
status: 200
```
```
type: org.apache.brooklyn.test.framework.TestHttpCall
name: Assert 200 OK
url: http://localhost:8081
applyAssertionTo: status
assert:
- isEqualTo: 200
```
=> Added utility `TestFrameworkAssertions` to address comments from #999

core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerExceptionHandlerTest.java
- Exposed exceptions in RebindTestUtils
=> BROOKLYN-193 Test skipping rebind failures for an entity config value

api/src/main/java/org/apache/brooklyn/api/entity/EntitySpec.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitySpecTest.java
If the memberspec of a dynamiccluster had a child entityspec then it would not be possible to set or expand the cluster to more than 1 node. This is because when addentity is called the parent entity is set on the childspec.  The dynamic cluster uses EntitySpec.create to duplicate the memberspec however this doesn't duplicate any children so the original and duplicate entityspecs share children.
When using EntitySpec.create to duplicate an entityspec this change duplicates children rather than attaching original child specs.
https://issues.apache.org/jira/browse/BROOKLYN-192
=> EntitySpec duplication should include children

core/src/main/java/org/apache/brooklyn/core/location/PortRanges.java, core/src/test/java/org/apache/brooklyn/core/location/PortRangesTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/text/StringEscapes.java
All values supported by `org.apache.brooklyn.core.location.PortRanges.fromString(String)` can now be included in `inboundPorts` in YAML blueprints.
Example:
```
name: "Port Range Example"
location: <cloud provider>
services:
- type: org.apache.brooklyn.entity.software.base.EmptySoftwareProcess
name: VM
provisioning.properties:
inboundPorts:
- 88
- 100-200
- 8080+
```
=> Add YAML port range support

parent/pom.xml, pom.xml, usage/launcher/pom.xml
Without this, Jetty will try to download XML schemas for the documents it processes. This means that Brooklyn requires a working connection to the public Internet. With this dependency, Jetty can discover the schemas it requires without an Internet connection.
=> BROOKLYN-197 Add jetty-schemas to launcher deps

DISCLAIMER, README.md, docs/README.md, docs/_build/config-production.yml, docs/_includes/footer.html, docs/_layouts/website-landing.html, docs/guide/dev/index.md, docs/website/community/how-to-contribute-docs.md, docs/website/developers/committers/release-process/announce.md, docs/website/learnmore/catalog/index.html
Remove the incubator disclaimer and boilerplate text, and change the web URLs to our new home at https://brooklyn.incubator.apache.org
=> Remove incubating references

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogClasspathDo.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemBuilder.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemDo.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java, core/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogItemBuilderTest.java, usage/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogEntitySummary.java, usage/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogItemSummary.java, usage/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogLocationSummary.java, usage/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogPolicySummary.java, usage/rest-server/pom.xml, usage/rest-server/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
This adds, for each catalog item, all its implemented interfaces as a tag. It also exposed catalog items' tags on the REST API.
This is based on the code provided by #1020
=> Adds support for interfaces tag on catalog items

core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/SshTool.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeed.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmToolResponse.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/pywinrm/Winrm4jTool.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeedTest.java
We want the interface/class within Brooklyn so that the rest of the code doesn't depend on winrm4j directly.
We also want to be able to swap out the Winrm4jTool for an alternative implementation, just through configuration.
Note that the unqualified interface name / class name are the same as the names in `io.cloudsoft.winrm4j.winrm.WinRmTool` and ` io.cloudsoft.winrm4j.winrm.WinRmToolResponse`. Is that a good idea? Any better suggestions for names?
=> Adds WinRmTool interface

software/base/src/test/java/org/apache/brooklyn/entity/AbstractEc2LiveTest.java, software/database/src/test/java/org/apache/brooklyn/entity/database/mariadb/MariaDbLiveEc2Test.java, software/database/src/test/java/org/apache/brooklyn/entity/database/mysql/MySqlLiveEc2Test.java, software/database/src/test/java/org/apache/brooklyn/entity/database/postgresql/PostgreSqlEc2LiveTest.java, software/messaging/src/test/java/org/apache/brooklyn/entity/messaging/rabbit/RabbitEc2LiveTest.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNode.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNodeImpl.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/AbstractMongoDBSshDriver.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/MongoDBServer.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/MongoDBServerImpl.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/riak/RiakNode.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/riak/RiakNodeImpl.java, software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNodeEc2LiveTest.java, software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/mongodb/MongoDBEc2LiveTest.java, software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/redis/RedisEc2LiveTest.java, software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/riak/RiakNodeEc2LiveTest.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss6ServerImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss6SshDriver.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7Server.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7ServerImpl.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/jboss/JBoss6ServerAwsEc2LiveTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7ServerAwsEc2LiveTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/tomcat/TomcatServerEc2LiveTest.java, utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java, utils/common/src/test/java/org/apache/brooklyn/util/ssh/IptablesCommandsTest.java
Important if the entity is running in a locked-down location, e.g. such that only ssh access to the VM is available. This adds configuration to disable the use of jmx, http, thrift (for Cassandra), mongodb client, etc.
There is also a PR to fix java install, failing for the reason described at http://serverfault.com/questions/637549/epel-repo-for-centos-6-causing-error?newreg=7c6019c0d0ae483c8bb3af387166ce49 - i.e. adding `yum upgrade -y ca-certificates --disablerepo=epel`.
=> Feature: entity monitoring disablable

usage/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, usage/rest-client/pom.xml, usage/rest-client/src/test/java/org/apache/brooklyn/rest/client/BrooklynApiRestClientTest.java
I incorrectly diagnosed the issue in #1060 ... so changes made reverted
Root cause was due to Swagger updates made in #1040 
`@ApiOperation()` annotation on `CatalogApi#create` had response type set to `javax.ws.rs.core.Response` causing the BrooklynApi to try and marshall the returned entity to that type
=> Reverting changes made in #1060 and fixed root cause

core/src/test/java/org/apache/brooklyn/util/core/ssh/BashCommandsIntegrationTest.java, core/src/test/resources/brooklyn/util/ssh/test_sudoers, utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
- it doesn't directly edit /etc/sudoers
- uses visudo to verify the prepared file
- added integration test
- excluded test sudoers file from rat plugin checks
=> SoftwareProcess.dontRequireTtyForSudo - sudoers file verification

karaf/itest/pom.xml, karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java, karaf/pom.xml, pom.xml
Unfortunately pax-exam-testng is not yet usable. We decided to switch to the junit runner until this gets resolved upstream (see https://ops4j1.jira.com/browse/PAXEXAM-698)
=> [BROOKLYN-183] Fix brooklyn-itest

usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/BaseTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/SimpleShellCommandTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/SimpleShellCommandTestImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensorImpl.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/SimpleShellCommandIntegrationTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestHttpCallTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSensorTest.java, usage/test-framework/src/test/resources/test-framework-examples/testhttpcall-examples.yml
At the moment in the test framework, as noted in [#1030](https://github.com/apache/incubator-brooklyn/pull/1030#issuecomment-158995925), when assertions fail it's not easy to see from the error text in the Activity log what went wrong. In particular if there are multiple assertions that failed this isn't apparent.
This update merges the assertion code from SimpleShellCommand and TestFrameworkAssertions to give:
- Updates test framework assertions so that multiple failures are described in the assertion failure message, such as
```
Assertions failed: exit code equals 1 stdout equals bogus stdout contains porkpie
```
- Supports generic 'actual' parameter, so we can avoid doing type coercions to String in
order to check assertions.
- Adds "hasTruthValue" condition.
=> Updates to Test framework assertions to support multiple assertion failures.

karaf/itest/pom.xml, karaf/pom.xml
Also follows convention used in other poms, to include relativePath
for parent, and to declare the artifactId+name before the parent.
The `BROOKLYN_VERSION` fix is very important for our release process, so we can easily update the version number everywhere.
Out of interest @CMoH why does kara/pom.xml depend on brooklyn rather than brooklyn-parent? I have not changed that here.
=> Fix itest/pom: include BROOKLYN_VERSION marker

software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlSshDriver.java
A downstream project was inadvertently setting this to an empty string. I've fixed the downstream, but MySQL should also play nicely
=> Guards against blank string in mysql.datadir

karaf/apache-brooklyn/pom.xml, karaf/commands/pom.xml
Similar idea to https://github.com/apache/incubator-brooklyn/pull/1077
=> Fix poms: include BROOKLYN_VERSION marker

usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/BaseTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/SimpleShellCommandTest.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/SimpleShellCommandTestImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java
This is in response to the comment on 1066, https://github.com/apache/incubator-brooklyn/pull/1066/#issuecomment-160699587.
=> Make default values for assertions config be immutable.

core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/SshAbstractTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmException.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/pywinrm/Winrm4jTool.java
Previously JcloudsLocation was hard-coded to use the winrm4j directly,
in waitForWinrmAvailable. Now it follows the same pattern as for 
ssh: it calls createTemporaryWinRmMachineLocation, and uses that for
the health check. This means any special config for an alternative
WinRmTool implementation will be respected.
=> JcloudsLocation: fix waitForWinRm, for alternate WinRmTool

usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java
The following test case will not work with the code as currently defined:
```yaml
name: testcase1
location:
mylocation
services:
- type: org.apache.brooklyn.entity.webapp.tomcat.TomcatServer
id: tomcatServer
timeout: 15m
- type: org.apache.brooklyn.test.framework.TestCase
name: TomServTest
brooklyn.children:
- type: org.apache.brooklyn.test.framework.TestSensor
target: $brooklyn:component("tomcatServer")
sensor: service.isUp
timeout: 1m
assert:
- equals: true
```
With the two entities (server and test) deployed independently instead of
within the same test case, the "checkAssertions" code will fail as it collects
all failures in AssertionSupport, when it should only collect those that
occur from the "Asserts.succeedsEventually".
Changing this code in this commit to allow tests to work. …
=> Fix assertions for 'succeeds eventually' behaviour.

parent/pom.xml, usage/camp/pom.xml, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampResolver.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, usage/launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/Windows7zipBlueprintLiveTest.java, usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ApidocResourceTest.java, usage/test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java
encountered the following apparently unnecessary jython imports while looking at building the proposed split brooklyn-server repo, have replaced with guava equivalents.
=> replaced jython imports with guava equivalents

usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCase.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCaseImpl.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCase.java, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCaseImpl.java
TestCase no longer extends BaseTest, but rather extends Entity directly. Added check in TestCaseImpl to ensure that only non-started children are startable. Added InfrastructureDeploymentTestCase
=> QA Updates for Clocker

software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/redis/RedisStoreSshDriver.java
Install fails on Ubuntu 14.04 in the Cisco cloud. gcc & make are already installed but headers are missing.
=> Redis install - make sure all build dependencies are installed

docs/website/download/index.md
Resulting mirror links resolve for the source and dist downloads on the generated site.
For example:
- https://www.apache.org/dyn/closer.lua/brooklyn/apache-brooklyn-0.8.0-incubating/apache-brooklyn-0.8.0-incubating-bin.tar.gz
=> Fix website download links (via ASF mirror)

software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlNode.java, software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlNodeImpl.java, software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlSshDriver.java
Remaining issues:
* 5.7.x introduces breaking changes in certain command/script behaviours, notably `mysql_install_db`, which is invoked during `customize`
* 5.5.x and 5.6.x working on Ubuntu but failing on RHEL / Centos / Amazon Linux due to missing perl dependencies
Will address these in subsequent PR.
=> Misc MySQL 5.5.x and 5.6.x fixes

usage/rest-api/pom.xml
- combined with https://github.com/swagger-api/swagger-codegen, it can generate rest bindings for multiple languages
=> Generate Swagger API Specification using a maven plugin

usage/rest-server/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/transform/EntityTransformer.java
Increment the priority because the config container is a `Set`. Server-side we are using an ordered set which results in correctly ordered items on the wire (as a list). Clients which use the java bindings though will push the items in an unordered set - so give them means to recover the correct order.
=> Proper ordering of catalog config

api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, core/src/main/java/org/apache/brooklyn/core/config/BasicConfigKey.java
The logic in some of the places assumes that the field is always non-null, initialized in the constructor. The assumption is broken when rebinding from an old state, because constructors are not called.
=> Rebind NPE fixes

core/src/main/java/org/apache/brooklyn/core/entity/EntityAsserts.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityFunctions.java, core/src/main/java/org/apache/brooklyn/core/feed/FeedConfig.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityFunctionsTest.java, software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/couchdb/CouchDBNodeImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss6ServerImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7ServerImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jetty/Jetty6ServerImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/tomcat/TomcatServerImpl.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/AbstractWebAppFixtureIntegrationTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/jetty/JettyWebAppFixtureIntegrationTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/tomcat/TomcatServerWebAppFixtureIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java
Entities that use `org.apache.brooklyn.entity.webapp.WebAppServiceMetrics#REQUEST_COUNT` are configured to republish the existing sensor value when a poll fails.
**Context**
The webapp entities (for Tomcat, JBoss, etc.) publish a request count sensor. `WebAppServiceMethods#connectWebAppServerPolicies(EntityLocal)` is used by `JavaWebAppSoftwareProcess` (among others) to enrich the sensor into values for `REQUESTS_PER_SECOND_LAST` and `REQUESTS_PER_SECOND_IN_WINDOW` sensors.
The clustered varieties of these entities (`DynamicWebAppCluster` and co.) enrich the enriched values into cluster-wide aggregates.
Enrichers are only updated when a value for the source sensor (request count) is published.
If an entity's process fails then the poll for the request count sensor fails and no value is …
=> Republish request count sensors on poll failure

docs/guide/dev/env/ide/eclipse.include.md, docs/guide/yaml/example_yaml/simple-appserver-with-location-byon.yaml, usage/cli/src/main/resources/brooklyn/default.catalog.bom
The byon syntax in the examples didn't work so these very minor changes modify the syntax to match https://brooklyn.apache.org/v/latest/ops/locations/#byon
=> fixed byon syntax for catalog template examples

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsWinRmMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/RebindJcloudsLocationLiveTest.java, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-aws-machine-aKEcbxKN, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-aws-parent-lCYB3mTb, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-aws-winrm-machine-KYSryzW8, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-aws-winrm-parent-fKc0Ofyn, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-azure-machine-VNapYjwp, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-azure-parent-briByOel
Work in progress:
* requires the same to be done for `JcloudsWinrmMachineLocation`
* requires more testing for backwards compatibility (see the unit test included here; but needs tested in the wild).
Previously JcloudsSshMachineLocation would persist the `NodeMetadata` and the `Template`, which pulled in lots of jclouds stuff. This was very brittle: if the NodeMetadata fields changed, or something like `AzureComputeTemplateOptions` fields changed, then rebind could fail.
This changes `JcloudsSshMachineLocation` to not persist node and template. Instead it persists the nodeId + imageId + privateAddresses + publicAddresses + hostname (i.e. the things in NodeMetadata that are most important).
For backwards compatibility, if on rebind it finds the node in the persisted state then it extracts …
=> Jclouds machines: do not persist NodeMetadata or Template

parent/pom.xml, software/webapp/src/main/java/org/apache/brooklyn/entity/dns/AbstractGeoDnsService.java, software/webapp/src/main/java/org/apache/brooklyn/entity/dns/AbstractGeoDnsServiceImpl.java, software/webapp/src/main/java/org/apache/brooklyn/entity/dns/geoscaling/GeoscalingDnsService.java, software/webapp/src/main/java/org/apache/brooklyn/entity/dns/geoscaling/GeoscalingDnsServiceImpl.java, software/webapp/src/test/java/org/apache/brooklyn/entity/dns/AbstractGeoDnsServiceTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/dns/geoscaling/GeoscalingIntegrationTest.java, software/webapp/src/test/java/org/apache/brooklyn/entity/dns/geoscaling/GeoscalingWebClientTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/GeoDnsServiceYamlTest.java, usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/geodns.yaml
A variety of improvements to the geo-DNS entities. In particular:
* Entities whose service state is not `RUNNING` are automatically excluded from the pool of targets. This can be disabled to maintain existing behaviour.
* The group to be tracked by `AbstractGeoDnsService` can be given in a config key, which means users don't need to call `setTargetEntityProvider` and thus that the service can be used from yaml.
=> GeoDns improvements

camp/camp-base/src/main/java/org/apache/brooklyn/camp/spi/resolve/PdpProcessor.java, camp/camp-base/src/main/java/org/apache/brooklyn/camp/spi/resolve/interpret/PlanInterpretationContext.java, core/src/main/java/org/apache/brooklyn/core/internal/BrooklynProperties.java, core/src/main/java/org/apache/brooklyn/core/internal/BrooklynPropertiesImpl.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/CampYamlParser.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/DeferredBrooklynProperties.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContext.java, core/src/test/java/org/apache/brooklyn/location/byon/ByonLocationResolverTest.java, docs/guide/ops/brooklyn_properties.md, docs/guide/ops/externalized-configuration.md, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/LocalBrooklynNodeImpl.java, usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/BrooklynCampPlatform.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigBrooklynPropertiesTest.java, usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/security/provider/ExplicitUsersSecurityProvider.java, usage/rest-server/src/main/java/org/apache/brooklyn/rest/util/json/BrooklynJacksonJsonProvider.java
An alternative implementation to https://github.com/apache/incubator-brooklyn/pull/1018 (i.e. replaces that PR).
=> support for external config in BrooklynProperties

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/internal/EntityConfigMap.java, core/src/main/java/org/apache/brooklyn/core/sensor/AttributeMap.java, core/src/test/java/org/apache/brooklyn/core/entity/AttributeMapTest.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityConcurrencyTest.java
Previously we were using a vanilla LinkedHashMap for storing attributes
(ever since the FEATURE_USE_BROOKLYN_LIVE_OBJECTS_DATAGRID_STORAGE
was disabled by default!)
Now uses synchronized set / synchronized map (rather than `ConcurrentMap`, as need to accept null values), with underlying `LinkedHashSet` to preserve order.
Adds `EntityConcurrencyTest` for concurrently:
- setting attributes (previously failed fairly often)
- setting config
- adding tags
- adding groups (previously failed sometimes)
- adding children
- adding locations
- adding policies
- adding enrichers
- adding feeds
=> Fix concurrent use of entity.setAttribute()

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/enricher/stock/reducer/Reducer.java, parent/pom.xml, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java, usage/downstream-parent/pom.xml, usage/launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java, usage/qa/pom.xml, usage/qa/src/test/java/org/apache/brooklyn/qa/downstreamparent/DownstreamParentTest.java, usage/qa/src/test/projects/downstream-parent-test/README, usage/qa/src/test/projects/downstream-parent-test/pom.xml, usage/qa/src/test/projects/downstream-parent-test/src/main/java/com/example/HelloEntity.java, usage/qa/src/test/projects/downstream-parent-test/src/main/java/com/example/HelloEntityImpl.java, usage/qa/src/test/projects/downstream-parent-test/src/main/resources/blueprint.yaml, usage/qa/src/test/projects/downstream-parent-test/src/main/resources/catalog.bom, usage/test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensorImpl.java
Removes the `Export-Package` manifest configuration from `brooklyn-downstream-parent` and adds a number of excludes of packages that are not bundles to `Import-Package`. 
Projects using downstream-parent can be loaded into catalogues via bundles by default. This can be tested by running `DownstreamParentTest` in the QA module.
=> Downstream-parent / OSGi

brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SameServerDriverLifecycleEffectorTasks.java, brooklyn-server/software/base/src/test/java/org/apache/brooklyn/entity/software/base/SameServerDriverLifecycleEffectorTasksTest.java
Previously any entity config with a value that TypeCoercions could coerce to PortRange was included in the list of ports.
=> Fix getRequiredOpenPorts in SameServerDriverLifecycleEffectorTasks

brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java
An entity with an instance of `attributeWhenReady` is serialised and then deserialised
=> Test correct persistence of attributeWhenReady

brooklyn-server/core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java
I want the activation of [brooklyn-tosca](https://github.com/cloudsoft/brooklyn-tosca/) to be configurable and to be enabled by default. At the moment any property beginning `brooklyn.experimental.feature` that is not defined in `BrooklynFeatureEnablement` defaults to `false` (because `Boolean.parseBoolean(null) == false`). This change allows downstream projects to explicitly configure defaults.
=> Expose BrooklynFeatureEnablement.setDefault

brooklyn-server/core/src/main/java/org/apache/brooklyn/core/location/geo/LocalhostExternalIpLoader.java, brooklyn-server/core/src/main/resources/org/apache/brooklyn/location/geo/external-ip-address-resolvers.txt
Remove shutdown IP address lookup service from list of resolvers.
Block the lookup methods until either all providers have been checked or the IP address has been resolved.
https://issues.apache.org/jira/browse/BROOKLYN-213
=> BROOKLYN-213 Fix localhost external IP loader

brooklyn-server/core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogXmlSerializer.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java, brooklyn-server/core/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogDtoTest.java
Fixes the serialized XML format so it can be deserialized later.
There's an explicit alias for `List.class`, so the actual object type is not dumped. Any non-ArrayList will fail deserialization as that's what the default for `Collection` is. 
Another positive side of the change is that we won't have function class references serialized.
=> Fix catalog XML deserialization

brooklyn-server/camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynAssemblyTemplateInstantiator.java, brooklyn-server/camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java
Previously, any catalog item of type “template” would always be wrapped
in a BasicApplication. This was being done in three places. The first
is ok; the second two are bad:
1. When deploying a top-level “template” from the catalog.
2. When referring to a “template” catalog item in a member-spec (e.g.
for a DynamicCluster)
3. When referring to a “template” catalog item in brooklyn.children.
@johnmccabe @ahgittin @neykov you'll be interested in this.
I don't like the approach (duplicating the fix in three places, to remove the wrapping app, for the different contexts that it might be used).
It would feel better for the YAML-parsing to *not* wrap the entity at all, unless there was a really good reason to (e.g. the catalog item consists of multiple top-level services defined in its yaml). …
=> YAML: don’t wrap sub-entities in BasicApplication

brooklyn-server/core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java
Previously the archetype SingleWebServerSample was failing to deploy as the generated proxy did not include the 'Application' interface
=> Adds all interfaces to proxy if deploying concrete application

brooklyn-server/server-cli/src/main/resources/brooklyn/default.catalog.bom
turning off sticky sessions in template 4 allows the user to very easily validate balancing in action by refreshing the browser where they'll see a different VanillaSoftwareProcess entity id and IP address as requests round robin across balancer members.
```
I am VanillaSoftwareProcessImpl{id=sqyei7aO}, part of the cluster.
```
```
I am running at 10.220.0.230, with on-box IP configuration:
```
=> turn off sticky sessions to allow easy balancing validation

brooklyn-server/karaf/features/src/main/feature/feature.xml, brooklyn-server/software/base/pom.xml
Add brooklyn-software-base, brooklyn-software-winrm and brooklyn-policy features.
Ignore for now python imports in brooklyn-software-base.
=> [BROOKLYN-183] Add karaf features

brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroup.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroupImpl.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/QuarantineGroup.java
Use of delegate to denote quarantine group membership in the gui is no longer required following #929
=> deprecate group.members.delegate and prevent delegate creation when adding to quarantine

brooklyn-server/rest/rest-client/src/main/java/org/apache/brooklyn/rest/client/util/http/BuiltResponsePreservingError.java
Calling getEntity on BuiltResponsePreservingError would propagate a previously caught and ignored exception. Because of this the output did not mention that getEntity was the line propagating the exception. We now throw an IllegalStateException to make it clear where the exception is coming from
=> Fixed issue with exceptions in Rest Client

brooklyn-docs/guide/yaml/winrm/index.md
- Short troubleshooting section that incorrect windows template can
cause timeouts or fail some deployments
- Settings to Use for an Unattended Installation in known limitations
section
=> WinRM docs for correct preparation of windows templates

brooklyn-library/software/database/src/main/resources/org/apache/brooklyn/entity/database/mysql/mysql.conf, brooklyn-library/software/database/src/main/resources/org/apache/brooklyn/entity/database/mysql/mysql_master.conf, brooklyn-library/software/database/src/main/resources/org/apache/brooklyn/entity/database/mysql/mysql_slave.conf
- it changes the default of sql_mode to include "NO_AUTO_CREATE_USER"
- it will prevent the GRANT statement from automatically creating new
user accounts unless authentication information is specified.
=> Additional security for MySQL

brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java
copy-pre-install-resources, pre-install, pre-install-command
It makes much more sense to include those in the skip install family.
These phases are barely used but still I think it simplifies the lifecycle if it is like this.
=> In skipInstall include also pre-install-command

brooklyn-library/software/messaging/src/main/java/org/apache/brooklyn/entity/messaging/rabbit/RabbitBroker.java, brooklyn-library/software/messaging/src/main/java/org/apache/brooklyn/entity/messaging/rabbit/RabbitSshDriver.java, brooklyn-library/software/messaging/src/main/resources/org/apache/brooklyn/entity/messaging/rabbit/rabbitmq.config
RabbitMQ to v.3.6.0
Erlang to v.18.2
RabbitMQ recommends Erlang 18. Release notes state:
Minimum required Erlang version is R16B03 for plain ("just TCP")
connections for all protocols 
and 17.5 for TLS ones (18.x is recommended for both).
The recommended provider for up to date Erlang versions is Erlang
Solutions now.
Supported platforms by Erlang Solutions are: CentOS, RHEL, Ubuntu and
Debian.
New Erlang versions for SUSE are provided via the openSUSE repositories
=> RabbitMQ upgrade

brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java, brooklyn-server/locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, brooklyn-server/pom.xml, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, brooklyn-server/software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java, brooklyn-server/software/winrm/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeed.java, brooklyn-server/software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, brooklyn-server/software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, brooklyn-server/software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java, brooklyn-server/software/winrm/src/test/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeedLiveTest.java
- This is a pure-java WinRM client, so removes the jython depenpdency.
- Also changes WinRmTool.executeScript(...) to executeCommand(…),
and WinRmMachineLocation.executeScript to executeCommand.
- Fixes WindowsPerformanceCounterFeedLiveTest
- Renames Winrm4jTool’s package (from pywinrm to winrm4j).
- Fixes imports that used org.python
The winrm4j 0.2.0 release is now available in maven central - http://search.maven.org/#artifactdetails%7Cio.cloudsoft.windows%7Cwinrm4j%7C0.2.0%7Cjar
=> winrm: switch to winrm4j v0.2.0, from 0.1.0

brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptySoftwareProcessYamlTest.java, brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptyWindowsProcessYamlTest.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptySoftwareProcessImpl.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcess.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcessDriver.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcessImpl.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcessWinRmDriver.java
- Includes EmptyWindowsProcess.USE_WINRM_MONITORING, for disabling checking of WinRM connectivity.
- Adds EmptySoftwareProcess.USE_SSH_MONITORING, for disabling checking of ssh connectivity.
With EmptyWindowsProcess, one can provision an entity that will not execute anything on the box. That makes it usable even if there is no direct WinRM connectivity to the box.
=> Feature: EmptyWindowsProcess

brooklyn-server/core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynShutdownHooks.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContext.java, brooklyn-server/rest/rest-server/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, brooklyn-server/rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java, brooklyn-server/rest/rest-server/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java, brooklyn-server/rest/rest-server/src/test/java/org/apache/brooklyn/rest/util/NoOpRecordingShutdownHandler.java, brooklyn-server/rest/rest-server/src/test/java/org/apache/brooklyn/rest/util/ServerStoppingShutdownHandler.java, brooklyn-server/server-cli/src/main/java/org/apache/brooklyn/cli/Main.java
call Main.terminate() in the main thread, rather than relying on shutdown hooks
fixes rest-initiated shutdown when using BrooklynJavascriptGuiLauncher
(looks like that has been broken since #771)
/cc @neykov does this look like a reasonable enhancement of your work in #771 ?
=> better shutdown

brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/InboundPortsUtils.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SameServerDriverLifecycleEffectorTasks.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SameServerEntity.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java, brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, brooklyn-server/software/base/src/test/java/org/apache/brooklyn/entity/software/base/SameServerDriverLifecycleEffectorTasksTest.java
Add config keys to `SoftwareProcess` governing the opening of ports based on sensor names, so it is explicit when you look at the config keys for the relevant entities.  ie, `SoftwareProcessImpl.getRequiredOpenPorts` uses a config key whose default value is this:
```
inboundPorts.configRegex=.*\.port
```
Also add a config option whose default value is this:
```
inboundPorts.autoInfer=true
```
If explicitly set to false, it turns off the opening of ports based on naming convention, and also those defined in Java entities that are of type PortRange.
Remove duplication of code between `SameServerDriverLifecycleEffectorTasks` and `SoftwareProcessImpl`.
Make login port (22) also a config key, not a constant, in `SameServerEntity`.
=> Better control over opening inbound ports

brooklyn-server/core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java, brooklyn-server/core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, brooklyn-server/core/src/test/java/org/apache/brooklyn/util/core/task/DynamicSequentialTaskTest.java, brooklyn-server/software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/jmx/JmxService.java, brooklyn-server/software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxFeedTest.java, brooklyn-server/test-support/src/main/java/org/apache/brooklyn/test/NetworkingTestUtils.java, brooklyn-server/utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java
seeing errors on jenkins server though it runs fine locally;
have patched what looks like one race, but not sure it explains the failure
at https://builds.apache.org/job/incubator-brooklyn-pull-requests/org.apache.brooklyn$brooklyn-core/2440/testReport/junit/org.apache.brooklyn.util.core.task/DynamicSequentialTaskTest/testCancelled/
where we are seeing an extra semaphore at the end of the test;
have added comments and logging in case it is seen again.
(locally all is well.)
=> fix race in DSTTest.testCancel

brooklyn-server/policy/src/test/java/org/apache/brooklyn/policy/ha/ConnectionFailureDetectorTest.java
the failure log is recorded at:
https://gist.github.com/davidx/1a21649a5e637b7b2a6a
=> mark ConnectionFailureDetectorTest.java as Integration because it requires ports accessible

brooklyn-dist/release/change-version.sh, brooklyn-server/core/src/main/java/org/apache/brooklyn/feed/ssh/SshPollConfig.java, brooklyn-server/core/src/test/java/org/apache/brooklyn/feed/ssh/SshFeedIntegrationTest.java, brooklyn-server/core/src/test/java/org/apache/brooklyn/feed/ssh/SshFeedTest.java
Fix the avoidance of executing the same command repeatedly, if an `SshFeed` is configured with multiple sensors that use the output of the same command.
=> Fix: SshFeed duplicate cmds
