apache/incubator-brooklyn

- pom.xml
This is the simple change that provides code coverage on a per project basis but doesn't do any coverage merging
> Upgrade cobertura plus minor fixes

- software/base/src/main/java/brooklyn/entity/basic/SoftwareProcess.java
- software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
- software/base/src/test/java/brooklyn/entity/basic/SoftwareProcessEntityTest.java
- software/base/src/test/java/brooklyn/entity/software/MachineLifecycleEffectorTasksTest.java
Separate flags for process and machine stop, better control with regard to the machine state.
> Finer-grained STOP effector parameters.

- core/src/main/java/brooklyn/util/ResourceUtils.java
- usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java
- usage/launcher/src/test/java/brooklyn/launcher/BrooklynWebServerTest.java
(since we do call it keystore url!)
> support URL for the keystore supplied to brooklyn web server

- usage/scripts/change-version.sh
* files with spaces
* fail-fast
* no matching files case
> Make change-versions.sh more resilient.

- api/src/main/java/brooklyn/management/ha/HighAvailabilityManager.java
- core/src/main/java/brooklyn/management/ha/HighAvailabilityManagerImpl.java
- core/src/main/java/brooklyn/management/internal/NonDeploymentManagementContext.java
- usage/jsgui/src/main/webapp/assets/css/base.css
- usage/jsgui/src/main/webapp/assets/js/view/application-add-wizard.js
- usage/jsgui/src/main/webapp/assets/js/view/ha-summary.js
- usage/jsgui/src/main/webapp/assets/js/view/home.js
- usage/jsgui/src/main/webapp/assets/tpl/app-add-wizard/create.html
- usage/jsgui/src/main/webapp/assets/tpl/home/applications.html
- usage/rest-api/src/main/java/brooklyn/rest/api/ServerApi.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/ServerResource.java
shows yaml tab (and nice message on catalog tab) if catalog is empty
server list is now after apps list, and there is a way to clear it (new `HighAvailabilityManagerImpl.publishClearNonMaster()` method, REST call, and button on main page)
> JS gui improvements - empty catalog and server list

- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsMachineNamer.java
- remove maxLenght for SoftLayer
> fix JcloudsMachineNamer

- core/src/main/java/brooklyn/management/entitlement/Entitlements.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/ServerResource.java
> Adds entitlement check to state checks

- core/src/main/java/brooklyn/entity/basic/BrooklynTaskTags.java
- software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java
- software/base/src/test/java/brooklyn/entity/brooklynnode/BrooklynNodeTest.java
Otherwise if there still are running tasks for the entity they will be canceled.
> Wait for STOP effector to complete before unamanging BrooklynNode

- core/src/main/java/brooklyn/entity/rebind/RebindIteration.java
- core/src/main/java/brooklyn/entity/rebind/RebindManagerImpl.java
- core/src/main/java/brooklyn/entity/rebind/persister/PersistenceActivityMetrics.java
introduce new class and new methods for each phase. (no real changes.)
> refactor RebindManager to have a RebindIteration

- camp/camp-base/src/main/java/io/brooklyn/camp/spi/AbstractResource.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/ApplicationComponent.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/Assembly.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/AssemblyTemplate.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/PlatformComponent.java
- fix for CAMP module: some setters on the builders were breaking the build with javac
- it also fixes javac compiler in intellij
@ahgittin and @neykov can you have a look?
> fix maven javac purity on JDK7

- software/webapp/src/main/java/brooklyn/entity/proxy/nginx/NginxDefaultConfigGenerator.java
- software/webapp/src/main/java/brooklyn/entity/proxy/nginx/NginxTemplateConfigGenerator.java
- software/webapp/src/main/resources/brooklyn/entity/proxy/nginx/server.conf
Make the template config closer to the NginxDefaultConfigGenerator, support non-domain config.
> nginx support for upstream https, disable SSLv3

- camp/camp-base/src/main/java/io/brooklyn/camp/spi/AbstractResource.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/ApplicationComponent.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/ApplicationComponentTemplate.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/Assembly.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/AssemblyTemplate.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/PlatformComponent.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/PlatformComponentTemplate.java
- camp/camp-base/src/main/java/io/brooklyn/camp/spi/PlatformRootSummary.java
Meant to be a part of #489 but got left off!  I think this is preferred over #493 because it keeps the visibility nice.
@andreaturli can you try this?
> More fixes for Java7 pure javac build

- core/src/main/java/brooklyn/catalog/CatalogPredicates.java
- core/src/main/java/brooklyn/management/classloading/OsgiBrooklynClassLoadingContext.java
- core/src/main/java/brooklyn/management/entitlement/EntitlementManagerAdapter.java
- core/src/main/java/brooklyn/management/entitlement/Entitlements.java
- core/src/main/java/brooklyn/management/internal/EffectorUtils.java
- core/src/main/java/brooklyn/management/internal/EntityChangeListener.java
- core/src/main/java/brooklyn/management/internal/EntityManagementSupport.java
- core/src/test/java/brooklyn/management/entitlement/AcmeEntitlementManagerTest.java
- core/src/test/java/brooklyn/management/entitlement/AcmeEntitlementManagerTestFixture.java
- core/src/test/java/brooklyn/management/entitlement/EntitlementsTest.java
- core/src/test/java/brooklyn/management/entitlement/EntityEntitlementTest.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/ApplicationResource.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/CatalogResource.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/EffectorResource.java
- usage/rest-server/src/main/java/brooklyn/rest/util/BrooklynRestResourceUtils.java
allows filtering based on arguments to effectors, access to catalog, and cleans up the pattern by which entitlement-supplying classes can be written
> Entitlements - effector args and catalog access

- core/src/main/java/brooklyn/config/render/RendererHints.java
- core/src/main/java/brooklyn/util/task/DynamicTasks.java
- software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
- software/nosql/src/main/java/brooklyn/entity/nosql/mongodb/AbstractMongoDBSshDriver.java
- usage/jsgui/src/main/webapp/assets/js/model/application.js
- usage/jsgui/src/main/webapp/assets/js/view/application-add-wizard.js
- usage/jsgui/src/main/webapp/assets/tpl/app-add-wizard/deploy.html
- usage/rest-api/src/main/java/brooklyn/rest/api/AccessApi.java
> None location

- core/src/main/java/brooklyn/util/file/ArchiveUtils.java
- core/src/test/java/brooklyn/util/file/ArchiveUtilsTest.java
- Fixes case where optionalTmpDir not supplied
- Adds various test cases
> Adds ArchiveUtilsTest + fixes ArchiveUtils

- core/src/main/java/brooklyn/BrooklynVersion.java
- docs/guide/misc/release-notes.md
- usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java
- usage/launcher/src/main/java/brooklyn/launcher/config/BrooklynDevelopmentModes.java
- usage/launcher/src/main/java/brooklyn/launcher/config/BrooklynGlobalConfig.java
- usage/launcher/src/main/java/brooklyn/launcher/config/CustomResourceLocator.java
closing streams, deprecating old BrooklynDevelopmentModes, and release notes
builds on #478 which was prematurely merged
@neykov does this address all your comments?
> code review fixes for CLI extensions

- docs/guide/ops/locations/index.md
@aledsage I don't think I need to go into much detail here but you may disagree.
> Notes on setting up BYON nodes

- docs/website/download/index.md
The current instructions are confusing.
> Clarify instructions

- docs/guide/dev/env/maven-build.md
… for those folks who blindly cut and paste …
> Added missing double quotes

- core/src/main/java/brooklyn/BrooklynVersion.java
- core/src/test/java/brooklyn/BrooklynVersionTest.java
change how we detect dev environment -- just look for a `classes` directory
> fix cobertura build - BROOKLYN-134

- usage/jsgui/src/main/webapp/assets/js/util/brooklyn-utils.js
- usage/jsgui/src/main/webapp/index.html
- usage/rest-server/src/main/java/brooklyn/rest/filter/BrooklynPropertiesSecurityFilter.java
Previously, clicking logout would leave the page at /logout. Trying to log in would then navigate to a URL such as /logout/#v1 etc
> Redirects web gui to root on logout to prevent login failure after logout

- core/src/main/java/brooklyn/basic/BrooklynObjectInternal.java
- core/src/main/java/brooklyn/entity/basic/AbstractEntity.java
- docs/website/developers/index.md
two minor grievances--
* eclipse groovy was giving a funny error due to config type incompatibility
* the dev docs should make it easier to find our jenkins server
> Misc tidies

- docs/guide/dev/code/tests.md
- docs/guide/dev/tips/index.md
- docs/guide/java/entities.md
- docs/guide/ops/persistence/index.md
We could also do with moving the persistence guidelines / best practices into somewhere more prominent (e.g. a top-level page)?
This PR hopefully gives the content required.
> Docs: improve rebind and SoftwareProcess docs

- software/base/src/main/java/brooklyn/entity/basic/lifecycle/ScriptHelper.java
- software/base/src/test/java/brooklyn/entity/AbstractEc2LiveTest.java
- software/database/src/test/java/brooklyn/entity/database/rubyrep/RubyRepEc2LiveTest.java
- software/messaging/src/test/java/brooklyn/entity/messaging/rabbit/RabbitEc2LiveTest.java
- software/network/src/test/java/brooklyn/entity/network/bind/BindDnsServerEc2LiveTest.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
- software/nosql/src/test/java/brooklyn/entity/nosql/couchbase/CouchbaseSyncGatewayEc2LiveTest.java
- software/webapp/src/test/java/brooklyn/entity/proxy/nginx/NginxEc2LiveTest.java
> Basho Riak - Linux Install

- locations/jclouds/src/main/java/brooklyn/location/jclouds/BrooklynImageChooser.java
> image chooser prefers id's containing the os name

- .gitignore
- pom.xml
- usage/rest-client/src/main/java/brooklyn/rest/client/BrooklynApi.java
Replace painful implementation of BrooklynApi HTTP authentication with proper one.
> Improve brooklyn-rest-client

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
- utils/common/src/main/java/brooklyn/util/ssh/BashCommands.java
- Move the utility methods to the appropriate
BashCommands class
> Riak Linux - fix

- core/src/main/java/brooklyn/entity/rebind/AbstractBrooklynObjectRebindSupport.java
- core/src/main/java/brooklyn/entity/rebind/dto/MementosGenerators.java
- core/src/main/java/brooklyn/entity/rebind/persister/BrooklynPersistenceUtils.java
- core/src/main/java/brooklyn/location/access/PortForwardManagerImpl.java
- core/src/main/java/brooklyn/util/task/system/ProcessTaskStub.java
- core/src/test/java/brooklyn/entity/rebind/RebindCatalogItemTest.java
- core/src/test/java/brooklyn/entity/rebind/RebindCatalogWhenCatalogPersistenceDisabledTest.java
- core/src/test/java/brooklyn/entity/rebind/RebindTestFixture.java
- core/src/test/java/brooklyn/location/access/PortForwardManagerRebindTest.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/BrooklynImageChooser.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
- software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynNodeImpl.java
- software/base/src/main/java/brooklyn/entity/java/JavaSoftwareProcessSshDriver.java
- software/webapp/src/main/java/brooklyn/entity/proxy/AbstractControllerImpl.java
- software/webapp/src/main/java/brooklyn/entity/proxy/LoadBalancer.java
- software/webapp/src/main/java/brooklyn/entity/webapp/JavaWebAppSshDriver.java
- software/webapp/src/test/java/brooklyn/entity/proxy/AbstractControllerTest.java
- usage/camp/src/test/resources/java-web-app-and-db-with-policy.yaml
confirmed working w jboss and brooklyn node in clocker.  i want to test with tomcat, and explore port-forward manager bug, then ready for merging.
> fixes for BrooklynNode and java appservers to run in clocker, using subnet hostname

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeDriver.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
- software/nosql/src/test/java/brooklyn/entity/nosql/riak/RiakClusterEc2LiveTest.java
Fixes some issues with Riak on Clocker. Replaces #562
> Updates to Riak for Clocker

- core/src/main/java/brooklyn/management/internal/LocalEntityManager.java
Relax synchronization in `LocalEntitymanager` to prevent a deadlock on rebind.
> Relax synchronisation in EntityManager

- usage/rest-server/src/test/java/brooklyn/rest/resources/UsageResourceTest.java
Context: this test is checking that the REST api for application-usage will report usage in the specified time range. If we ask for usage between `Wed Mar 18 11:45:25 GMT 2015` and `Wed Mar 18 11:45:25 GMT 2015` then we expect to be told about all apps that were in use during that single second (and not to be told about the usage of those apps outside of that specific second).
- Was failing occasionally if the requested start/end date rounded down to a different value than the postStart date.
- I suspect 1 in 1000 chance, because depended if afterPostStart was in a different second from postStart - it was adding 1ms to it. I suspect the original intent was to add 1 second.
> Fix UsageResourceTest.testListApplicationUsages

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java
Blocks on the `joinCluster` effector task before starting the `commitCluster` effector.
> Wait for join to finish before committing cluster

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
@grkvlt could you please have a look?
> add main uri

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java
Add an enricher that shows the Riak URI from #570 on the cluster entity
> Add URI enricher for Riak cluster

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakCluster.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeDriver.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeImpl.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
This includes #574 and also some other minor Riak fixes
> Fix issue with Riak nodes not leaving cluster

- core/src/main/java/brooklyn/location/basic/AbstractLocation.java
Allows persisting of locations with dynamically added extensions
> Change extension map to a reference

- software/webapp/src/main/java/brooklyn/entity/webapp/JavaWebAppSshDriver.java
**WARN:** The fix changes the semantics of the deploy method. Previously it always succeeded regardless of the result of the copy operation. Now it will fail if either the copy or the rename operations fail.
Uploading the file directly to the webapps folder results in autodeploy triggering before the upload is complete. A problem arises when autodeploy triggers in the same second (before) the upload completes - it will fail due to incomplete file, but will not retry because the timestamp of the file won't change. Change deploy to upload to a temporary file and rename it to a .war only when done. This has a few benefits:
* The application won't be undeployed at the start of the upload and be down for the duration of the upload
* Once the server observers the updated file we can be sure …
> web app deploy - use temporary file for upload

- core/src/main/java/brooklyn/location/geo/GeoBytesHostGeoLookup.java
- core/src/main/java/brooklyn/location/geo/UtraceHostGeoLookup.java
- core/src/test/java/brooklyn/location/geo/HostGeoLookupIntegrationTest.java
- examples/simple-web-cluster/src/main/resources/brooklyn/demo/nodejs-todo.yaml
- usage/jsgui/src/main/webapp/assets/js/router.js
JS gui warning and stale integration test
> Misc minor fixes

- software/messaging/pom.xml
- software/messaging/src/main/java/brooklyn/entity/messaging/rabbit/RabbitBroker.java
- software/messaging/src/main/java/brooklyn/entity/messaging/rabbit/RabbitBrokerImpl.java
- software/messaging/src/main/java/brooklyn/entity/messaging/rabbit/RabbitSshDriver.java
- software/messaging/src/main/resources/brooklyn/entity/messaging/rabbit/rabbitmq.config
Add flag enableManagementPlugin defaulting to false
> Rabbit mq management flag

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
Fix installing from package url on redhat based distro
> Riak - Fix dependencies installing

- usage/rest-api/src/main/java/brooklyn/rest/domain/EntitySummary.java
made brooklyn.rest.domain.EntitySummary Serializable
> made entity summary Serializable

- policy/src/main/java/brooklyn/policy/ha/AbstractFailureDetector.java
- policy/src/main/java/brooklyn/policy/ha/ConditionalSuspendPolicy.java
- policy/src/main/java/brooklyn/policy/ha/ConnectionFailureDetector.java
- policy/src/main/java/brooklyn/policy/ha/ServiceFailureDetector.java
- policy/src/main/java/brooklyn/policy/ha/ServiceRestarter.java
- policy/src/main/java/brooklyn/policy/ha/SshMachineFailureDetector.java
- policy/src/test/java/brooklyn/policy/ha/ServiceFailureDetectorTest.java
* SshConnectionFailure emits CONNECTION_FAILURE if it can't make ssh connection to the machine of the entity
* ConditionalSuspendPolicy suspends a target policy if it receives a sensor event (CONNECTION_FAILURE by default)
> new policies: SshConnectionFailure, ConditionalSuspendPolicy

- software/nosql/src/test/java/brooklyn/entity/nosql/riak/RiakNodeSoftlayerLiveTest.java
> Riak - Add SoftlayerTest

- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNode.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakNodeSshDriver.java
- additional config moved from the RiakEnterpriseNode
- bump up default Riak version
> Store additional config in the riak.conf

- usage/launcher/src/main/java/brooklyn/launcher/BrooklynWebServer.java
Use non-blocking HTTPS connector, HTTP case was already using non-blocking.
HTTPS connector wasn't setting the bind address - something to have in mind as could lead to unexpected behaviour changes in existing installations.
> Non-blocking jetty connector for https

- core/src/main/java/brooklyn/enricher/basic/AbstractMultipleSensorAggregator.java
- core/src/main/java/brooklyn/entity/basic/ServiceStateLogic.java
- core/src/test/java/brooklyn/entity/basic/ServiceStateLogicTest.java
Also ignore SERVICE_UP failures from non-RUNNING children. Avoids setting the parent on fire while spinning up a child. /cc @ahgittin as he was the initial contributor of the SERVICE_UP quorum logic.
> Coerce aggregated sensor values

- core/src/main/java/brooklyn/entity/basic/EntityPredicates.java
- core/src/test/java/brooklyn/entity/basic/EntityPredicatesTest.java
- usage/rest-api/src/main/java/brooklyn/rest/api/ApplicationApi.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/ApplicationResource.java
And uses as optional query parameter in ApplicationApi.list.
> EntityPredicates.hasInterfaceMatching

- locations/jclouds/src/main/java/org/jclouds/ec2/compute/domain/EC2HardwareBuilder.java
fixes https://issues.apache.org/jira/browse/BROOKLYN-140
as noted, when new jclouds lands we should revert this
@duncangrant can you let us know if this fixes your problem?
> temporary local copy of fix for HVM/paravirtual issue on AWS

- examples/simple-web-cluster/src/main/resources/brooklyn/demo/nodejs-riak-todo.yaml
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakCluster.java
- software/nosql/src/main/java/brooklyn/entity/nosql/riak/RiakClusterImpl.java
- software/webapp/src/main/java/brooklyn/entity/webapp/nodejs/NodeJsWebAppSshDriver.java
- Refactoring the NodeJsWebAppSshDriver .
Install packages from package.json as non-root
> Nodejs riak sample app

- core/src/test/java/brooklyn/util/ResourceUtilsHttpTest.java
- pom.xml
replace LocalTestServer usage with HttpServer as per this [thread](http://mail-archives.apache.org/mod_mbox/hc-httpclient-users/201504.mbox/%3C1429533016.21609.7.camel@apache.org%3E).
> bump httpclient version

- core/src/main/java/brooklyn/entity/basic/Lifecycle.java
- core/src/test/java/brooklyn/entity/basic/LifecycleTransitionTest.java
> Fix String -> Lifecycle coercion for ON_FIRE

- software/webapp/src/main/java/brooklyn/entity/proxy/nginx/NginxController.java
Tested with a `ControlledDynamicWebAppCluster` with both http and https protocols.
> Upgrade nginx to latest stable version (1.8.0)

- software/base/src/main/java/brooklyn/entity/basic/EmptySoftwareProcessSshDriver.java
if pre- and post- install and launch commands are set for EmptySoftwareProcess, run them
> allow commands for EmptySoftwareProcess

- software/base/src/main/java/brooklyn/entity/software/ssh/SshCommandEffector.java
- software/base/src/main/java/brooklyn/entity/software/ssh/SshCommandSensor.java
fixes bug if ssh sensor used with empty software process entity, where run dir isn't yet created
> ssh command sensor allows configuring the dir where it runs

- software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynEntityMirror.java
- software/base/src/main/java/brooklyn/entity/brooklynnode/BrooklynEntityMirrorImpl.java
- usage/launcher/src/test/java/brooklyn/entity/brooklynnode/BrooklynEntityMirrorIntegrationTest.java
Also extract the catalogItemId in a separate attribute for easier access.
> Mirror summary for BrooklynEntityMirror

- software/base/src/main/java/brooklyn/entity/chef/ChefConfig.java
- software/base/src/main/java/brooklyn/entity/chef/ChefLifecycleEffectorTasks.java
- software/base/src/main/java/brooklyn/entity/chef/KnifeConvergeTaskFactory.java
- software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
without this nodes get left registered at the chef server.  needs testing.
> do the node and client deletion as part of stopping a chef node

- locations/jclouds/src/main/java/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java
- locations/jclouds/src/test/java/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizerTest.java
* Class is no longer final. Useful methods are exposed to subclasses.
* 0.0.0.0/0 used for CIDR for SSH so that Brooklyn failing over doesn't break its SSH access to machines.
* Incorporates SecurityGroupDefinitions.
* Adds ICMP permission to shared group.
* Predicate<Exception> can be provided to indicate that failed requests may be retried.
* Includes AwsExceptionRetryPredicate to retry InvalidGroup.InUse, DependencyViolation and RequestLimitExceeded errors.
> Improvements to JcloudsLocationSecurityGroupCustomizer

- core/src/main/java/brooklyn/entity/basic/EntityInternal.java
- usage/rest-api/src/main/java/brooklyn/rest/api/ApplicationApi.java
- usage/rest-client/pom.xml
- usage/rest-client/src/main/java/brooklyn/rest/client/BrooklynApi.java
- usage/rest-client/src/main/java/brooklyn/util/http/BuiltResponsePreservingError.java
- usage/rest-client/src/test/java/brooklyn/rest/client/ApplicationResourceIntegrationTest.java
- usage/rest-client/src/test/java/brooklyn/rest/client/BrooklynApiRestClientTest.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/ApplicationResource.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/CatalogResource.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/EntityConfigResource.java
- usage/rest-server/src/main/java/brooklyn/rest/resources/PolicyConfigResource.java
- usage/rest-server/src/main/java/brooklyn/rest/security/provider/DelegatingSecurityProvider.java
- usage/rest-server/src/main/java/brooklyn/rest/transform/LocationTransformer.java
- usage/rest-server/src/main/java/brooklyn/rest/util/BrooklynRestResourceUtils.java
- usage/rest-server/src/main/java/brooklyn/rest/util/json/MultimapSerializer.java
- usage/rest-server/src/test/java/brooklyn/rest/BrooklynRestApiLauncherTestFixture.java
- usage/rest-server/src/test/java/brooklyn/rest/domain/ApplicationTest.java
- usage/rest-server/src/test/java/brooklyn/rest/domain/LocationSummaryTest.java
- usage/rest-server/src/test/java/brooklyn/rest/resources/ApplicationResourceIntegrationTest.java
- usage/rest-server/src/test/java/brooklyn/rest/resources/EntityConfigResourceTest.java
- usage/rest-server/src/test/java/brooklyn/rest/resources/LocationResourceTest.java
- usage/rest-server/src/test/java/brooklyn/rest/resources/ServerResourceTest.java
- usage/rest-server/src/test/java/brooklyn/rest/testing/mocks/EverythingGroupImpl.java
- usage/rest-server/src/test/java/brooklyn/rest/testing/mocks/NameMatcherGroupImpl.java
- usage/rest-server/src/test/java/brooklyn/rest/util/json/BrooklynJacksonSerializerTest.java
> fix and test better rest client

- pom.xml
The JsonPath was updated to last available version
> FIX: library JsonPath was updated to 2.0.0

- software/base/src/main/java/brooklyn/entity/basic/AbstractSoftwareProcessSshDriver.java
- software/base/src/main/java/brooklyn/entity/java/JavaSoftwareProcessSshDriver.java
- software/base/src/main/java/brooklyn/entity/java/UsesJava.java
- software/base/src/test/java/brooklyn/entity/java/JavaSoftwareProcessSshDriverIntegrationTest.java
- software/nosql/src/main/java/brooklyn/entity/nosql/cassandra/CassandraNodeSshDriver.java
- software/nosql/src/test/java/brooklyn/entity/nosql/riak/RiakNodeIntegrationTest.java
- software/nosql/src/test/java/brooklyn/entity/nosql/riak/RiakNodeSoftlayerLiveTest.java
- add more control to the java version installed for the entities that UsesJava
> add support to control java version installed

- core/src/main/java/brooklyn/entity/basic/Attributes.java
- core/src/main/java/brooklyn/entity/basic/Sanitizer.java
- core/src/main/java/brooklyn/location/basic/WinRmMachineLocation.java
- core/src/test/java/brooklyn/entity/basic/SanitizerTest.java
- core/src/test/java/brooklyn/util/ResourceUtilsHttpTest.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationConfig.java
- locations/jclouds/src/main/java/brooklyn/policy/os/AdvertiseWinrmLoginPolicy.java
- locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationTest.java
- locations/jclouds/src/test/java/brooklyn/policy/os/AdvertiseWinrmLoginPolicyTest.java
- software/base/src/main/java/brooklyn/entity/basic/VanillaWindowsProcess.java
- software/base/src/main/java/brooklyn/entity/basic/VanillaWindowsProcessImpl.java
- software/base/src/main/java/brooklyn/entity/basic/VanillaWindowsProcessWinRmDriver.java
- improved support for windows credentials and
for sshHostAndPortOverride
> Windows support improvements in JcloudsLocation

- core/src/main/java/brooklyn/util/internal/Repeater.java
remove final in order to fix variable initialization concern
> Fix for Java 8 compile error

- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
Will be NOP until the jclouds version is bumped to include https://github.com/jclouds/jclouds/pull/756, probably `1.9.1`.
> Put user metadata into SL notes.

- core/src/main/java/brooklyn/entity/basic/AbstractEntity.java
- core/src/test/java/brooklyn/event/feed/function/FunctionFeedTest.java
Adding the same feed object a second time would stop it, ignore the call instead. Adding the same object twice is very common when `FEATURE_FEED_REGISTRATION_PROPERTY` is enabled, because blueprints already add it manually.
Fixes `NginxRebindWithHaIntegrationTest.testChangeModeFailureStopsTasksButHappyUponResumption`, which enables `FEATURE_FEED_REGISTRATION_PROPERTY`.
> Ignore entity.addFeed(...) call with same feed object

- docs/guide/ops/locations/index.md
This describes the issue discussed on #705
https://github.com/apache/incubator-brooklyn/pull/705
> Describes AWS VPC issue

- usage/camp/src/test/java/io/brooklyn/camp/brooklyn/JavaWebAppsIntegrationTest.java
- usage/camp/src/test/resources/java-web-app-and-db-with-function.yaml
- usage/camp/src/test/resources/java-web-app-and-db-with-policy.yaml
- usage/camp/src/test/resources/java-web-app-simple.yaml
- usage/camp/src/test/resources/visitors-creation-script.sql
- io.brooklyn.camp.brooklyn.JavaWebAppsIntegrationTest.testWithDbDeploy()
- io.brooklyn.camp.brooklyn.JavaWebAppsIntegrationTest.testWithPolicyDeploy()
> Fixing Integration tests for 0.7.0

- examples/simple-web-cluster/src/test/java/brooklyn/demo/RebindWebClusterDatabaseExampleAppIntegrationTest.java
- software/webapp/src/test/java/brooklyn/entity/proxy/nginx/NginxRebindIntegrationTest.java
- software/webapp/src/test/java/brooklyn/entity/proxy/nginx/NginxUrlMappingIntegrationTest.java
- usage/launcher/src/test/java/brooklyn/entity/brooklynnode/BrooklynEntityMirrorIntegrationTest.java
- usage/launcher/src/test/resources/vanilla-software-with-child-blueprint.yaml
- brooklyn.entity.brooklynnode.BrooklynEntityMirrorIntegrationTest
- brooklyn.entity.basic.VanillaSoftwareYamlTest
- brooklyn.demo.RebindWebClusterDatabaseExampleAppIntegrationTest
- NginxUrlMappingIntegrationTest
- NginxRebindIntegrationTest
> Fixing tests

- core/src/main/java/brooklyn/location/basic/ByonLocationResolver.java
- core/src/main/java/brooklyn/util/internal/ssh/ShellAbstractTool.java
> Fix SshMachineLocation unable to connect

- software/messaging/src/main/java/brooklyn/entity/messaging/kafka/KafkaZooKeeperSshDriver.java
- software/messaging/src/test/java/brooklyn/entity/messaging/kafka/KafkaIntegrationTest.java
- software/messaging/src/test/java/brooklyn/entity/messaging/kafka/KafkaSupport.java
> Kafka - fix escaping

- usage/jsgui/src/main/webapp/assets/js/view/effector-invoke.js
- usage/jsgui/src/main/webapp/assets/tpl/apps/param.html
- usage/jsgui/src/test/javascript/specs/model/effector-spec.js
- usage/jsgui/src/test/javascript/specs/view/effector-invoke-spec.js
- usage/rest-api/src/test/resources/fixtures/effector-summary-list.json
> Boolean effector parameters are rendered as checkboxes.

- core/src/main/java/brooklyn/entity/basic/EntityDynamicType.java
- core/src/main/java/brooklyn/entity/effector/Effectors.java
- core/src/test/java/brooklyn/entity/basic/DynamicEntityTest.java
Not sure if this is controversial.
> Add EntityDynamicType.removeEffector(Effector)

- sandbox/nosql/pom.xml
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastCluster.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastClusterImpl.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastNode.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastNodeDriver.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastNodeImpl.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastNodeSshDriver.java
- sandbox/nosql/src/main/resources/brooklyn/entity/nosql/hazelcast/hazelcast-brooklyn.xml
- sandbox/nosql/src/test/java/brooklyn/entity/nosql/hazelcast/HazelcastClusterEc2LiveTest.java
- sandbox/nosql/src/test/java/brooklyn/entity/nosql/hazelcast/HazelcastClusterSoftlayerLiveTest.java
A copy of #642 to squash the commits.
> BROOKLYN-143 - support for Hazelcast (PR 642)

- docs/guide/dev/tips/troubleshooting-exceptions.md
- examples/simple-web-cluster/src/main/java/org/apache/brooklyn/demo/WebClusterDatabaseExampleGroovy.groovy
- usage/launcher/src/test/java/brooklyn/launcher/BrooklynLauncherRebindCatalogTest.java
See individual descriptions of each commit.
> Minor improvements, incorporating comments from other merged PRs

- core/src/main/resources/brooklyn/location/basic/os-details.sh
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
- software/base/src/test/java/brooklyn/entity/AbstractEc2LiveTest.java
- software/base/src/test/java/brooklyn/entity/machine/MachineEntityEc2LiveTest.java
- usage/rest-server/src/main/java/brooklyn/rest/transform/LocationTransformer.java
- usage/rest-server/src/test/java/brooklyn/rest/resources/LocationResourceTest.java
And some other minor fixes - see separate commits for "Fix jclouds createUser..." and "Fix REST api location returning config"
> Fix SUSE on aws-ec2

- docs/_build/make-javadoc.sh
- docs/guide/ops/brooklyn_properties.md
- docs/guide/ops/install-on-server.md
- docs/guide/ops/locations/index.md
- docs/guide/ops/requirements.md
A few fixes made to support the 0.7.0-incubating release that need to be backported to `master`.
> Fixes from 0.7.0

- docs/_build/config-production.yml
- docs/_config.yml
- docs/website/download/index.md
- docs/website/download/verify.md
- docs/website/meta/versions.md
I've been a bit presumptious and already uploaded these changes to the public website, so they can be reviewed there. If any changes are needed to this PR I will of course update the website again.
> Website updates for 0.7.0-incubating release

- api/src/main/java/brooklyn/location/BasicMachineLocationCustomizer.java
- api/src/main/java/brooklyn/location/MachineLocationCustomizer.java
- core/src/main/java/brooklyn/location/basic/ByonLocationResolver.java
- core/src/main/java/brooklyn/location/basic/FixedListMachineProvisioningLocation.java
- core/src/main/java/brooklyn/location/basic/Machines.java
- core/src/main/java/brooklyn/location/basic/SshMachineLocation.java
- core/src/main/java/brooklyn/location/basic/WinRmMachineLocation.java
- core/src/main/java/brooklyn/location/cloud/CloudLocationConfig.java
- core/src/test/java/brooklyn/location/basic/FixedListMachineProvisioningLocationTest.java
- core/src/test/java/brooklyn/location/basic/RecordingMachineLocationCustomizer.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocation.java
- locations/jclouds/src/main/java/brooklyn/location/jclouds/JcloudsLocationConfig.java
- locations/jclouds/src/test/java/brooklyn/location/jclouds/JcloudsLocationTest.java
- software/base/src/main/java/brooklyn/entity/basic/SoftwareProcess.java
- software/base/src/main/java/brooklyn/entity/software/MachineInitTasks.java
- software/base/src/main/java/brooklyn/entity/software/MachineLifecycleEffectorTasks.java
- software/webapp/src/test/java/brooklyn/entity/webapp/tomcat/TomcatServerEc2LiveTest.java
- usage/camp/src/test/java/io/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java
And a few other things! See individual commits.
> Feature: BYON port mapping

- core/src/main/java/brooklyn/basic/BrooklynObjectInternal.java
- core/src/main/java/brooklyn/entity/basic/AbstractEntity.java
- core/src/main/java/brooklyn/entity/basic/EntityConfigMap.java
- core/src/main/java/brooklyn/location/basic/AbstractLocation.java
- core/src/main/java/brooklyn/location/basic/FixedListMachineProvisioningLocation.java
- core/src/main/java/brooklyn/policy/basic/AbstractEntityAdjunct.java
- core/src/main/java/brooklyn/policy/basic/ConfigMapImpl.java
- core/src/main/java/brooklyn/util/config/ConfigBag.java
- core/src/test/java/brooklyn/location/basic/FixedListMachineProvisioningLocationTest.java
- parent/pom.xml
- software/base/src/main/java/brooklyn/entity/software/MachineInitTasks.java
- software/base/src/test/java/brooklyn/entity/basic/DoNothingSoftwareProcess.java
- software/base/src/test/java/brooklyn/entity/basic/DoNothingSoftwareProcessDriver.java
- software/base/src/test/java/brooklyn/entity/basic/DoNothingSoftwareProcessImpl.java
- usage/camp/pom.xml
- usage/camp/src/test/java/io/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java
- usage/downstream-parent/pom.xml
See more detailed description in each commit.
> BYON: machine gets extra conf for duration of use

- docs/guide/ops/brooklyn_properties.md
- usage/rest-server/src/main/java/brooklyn/rest/security/provider/LdapSecurityProvider.java
Added an example brooklyn.properties for ldap
> LDAP authentication doc

- core/src/test/java/brooklyn/entity/group/DynamicClusterTest.java
- software/nosql/src/main/java/brooklyn/entity/nosql/redis/RedisClusterImpl.java
RedisCluster did not expose any sensors, so this adds basic information about the master node like host address and Redis port.
> Add basic sensors to RedisCluster

- sandbox/extra/src/main/java/brooklyn/entity/salt/SaltStackMaster.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastCluster.java
- sandbox/nosql/src/main/java/brooklyn/entity/nosql/hazelcast/HazelcastNode.java
> Fix imports missing from #789

- core/src/main/java/brooklyn/entity/basic/BasicStartableImpl.java
- core/src/main/java/brooklyn/entity/basic/ServiceStateLogic.java
- core/src/test/java/brooklyn/enricher/EnrichersTest.java
- core/src/test/java/brooklyn/entity/basic/AttributeMapTest.java
- core/src/test/java/brooklyn/entity/basic/BasicStartableTest.java
- core/src/test/java/brooklyn/entity/basic/EntityLocationsTest.java
- core/src/test/java/brooklyn/entity/basic/EntitySubscriptionTest.java
- core/src/test/java/brooklyn/entity/basic/EntityTypeTest.java
- core/src/test/java/brooklyn/entity/group/DynamicClusterTest.java
- core/src/test/java/brooklyn/policy/basic/PolicySubscriptionTest.java
- core/src/test/java/org/apache/brooklyn/entity/basic/RecordingSensorEventListener.java
- software/webapp/src/test/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterIntegrationTest.java
- software/webapp/src/test/java/brooklyn/entity/webapp/ControlledDynamicWebAppClusterTest.java
And adds useful test class `RecordingSensorEventListener`.
> BasicStartable entities transition through expected lifecycle states

- storage/hazelcast/src/main/java/org/apache/brooklyn/internal/storage/impl/hazelcast/EntityId.java
- storage/hazelcast/src/main/java/org/apache/brooklyn/internal/storage/impl/hazelcast/EntityStreamSerializer.java
- storage/hazelcast/src/main/java/org/apache/brooklyn/internal/storage/impl/hazelcast/HazelcastDataGrid.java
- storage/hazelcast/src/main/java/org/apache/brooklyn/internal/storage/impl/hazelcast/HazelcastDataGridFactory.java
- storage/hazelcast/src/test/java/org/apache/brooklyn/storage/impl/hazelcast/HazelcastStorageTest.java
> brooklyn-storage-hazelcast: add org.apache package prefix

- examples/simple-web-cluster/src/main/java/org/apache/brooklyn/demo/WebClusterDatabaseExampleGroovy.groovy
- sandbox/database/src/main/java/org/apache/brooklyn/entity/database/derby/DerbyDatabase.java
- sandbox/database/src/main/java/org/apache/brooklyn/entity/database/derby/DerbyDatabaseSshDriver.java
- sandbox/database/src/main/java/org/apache/brooklyn/entity/database/derby/DerbySchema.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/database/postgresql/PostgreSqlNodeSaltImpl.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltConfig.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltConfigs.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltLifecycleEffectorTasks.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltStackMaster.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltStackMasterSshDriver.java
- sandbox/extra/src/main/java/org/apache/brooklyn/entity/salt/SaltTasks.java
- sandbox/extra/src/test/java/org/apache/brooklyn/entity/database/postgresql/PostgreSqlSaltLiveTest.java
- sandbox/extra/src/test/java/org/apache/brooklyn/entity/salt/SaltConfigsTest.java
- sandbox/extra/src/test/java/org/apache/brooklyn/entity/salt/SaltLiveTestSupport.java
- sandbox/monitoring/src/main/java/org/apache/brooklyn/entity/monitoring/zabbix/ZabbixFeed.java
- sandbox/monitoring/src/main/java/org/apache/brooklyn/entity/monitoring/zabbix/ZabbixMonitored.java
- sandbox/monitoring/src/main/java/org/apache/brooklyn/entity/monitoring/zabbix/ZabbixPollConfig.java
- sandbox/monitoring/src/main/java/org/apache/brooklyn/entity/monitoring/zabbix/ZabbixServer.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastCluster.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastClusterImpl.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastNode.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastNodeImpl.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastNodeSshDriver.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/infinispan/Infinispan5Server.java
- sandbox/nosql/src/main/java/org/apache/brooklyn/entity/nosql/infinispan/Infinispan5SshDriver.java
- sandbox/nosql/src/test/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastClusterEc2LiveTest.java
- sandbox/nosql/src/test/java/org/apache/brooklyn/entity/nosql/hazelcast/HazelcastClusterSoftlayerLiveTest.java
- sandbox/nosql/src/test/java/org/apache/brooklyn/entity/nosql/infinispan/Infinispan5ServerIntegrationTest.groovy
- In sandbox and in groovy files
> Fix missing org.apache.brooklyn imports

- api/src/main/java/org/apache/brooklyn/api/catalog/CatalogItem.java
- api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/CatalogItemMemento.java
- camp/camp-base/src/main/java/org/apache/brooklyn/camp/spi/resolve/PdpProcessor.java
- core/src/main/java/org/apache/brooklyn/core/catalog/CatalogPredicates.java
- core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java
- core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemBuilder.java
- core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemDo.java
- core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemDtoAbstract.java
- core/src/main/java/org/apache/brooklyn/core/location/CatalogLocationResolver.java
- core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicCatalogItemRebindSupport.java
- core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/BasicCatalogItemMemento.java
- core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/MementosGenerators.java
- core/src/test/java/org/apache/brooklyn/core/catalog/CatalogPredicatesTest.java
- core/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogVersioningTest.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindOptions.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java
- usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlRebindTest.java
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlRebindTest.java
- usage/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java
- usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java
- usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
As discussed on mailing list.
(I still need to rebase this against master, after all the package renames, so it cannot yet be merged).
> Feature: catalog item disabled

- software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java
- See comments / discussion in https://github.com/apache/incubator-brooklyn/pull/866
> Fix AbstractSoftwareProcessWinRmDriver tags

- software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java
Make SoftwareProcessImpl *much* fussier about which config it implicitly adds to the list of required open ports.
> Don't treat *all* config as a "required open port"

- docs/website/developers/committers/release-process/environment-variables.md
- docs/website/developers/committers/release-process/make-release-artifacts.md
- docs/website/developers/committers/release-process/prerequisites.md
- docs/website/developers/committers/release-process/release-version.md
- docs/website/download/index.md
- usage/dist/licensing/overrides.yaml
- usage/jsgui/src/main/license/source-inclusions.yaml
This tidies the release process instructions (which were excellent, @rdowner !).
It also improves a problem with the download links at Apache (on top of #873).
And it adds `r.js` which I think completes addressing the comments on licenses from the 0.7.0-incubating release, /cc @hzbarcea .
For reference the comments there were:
> LICENCE is missing standard appendix
addressed with LICENSE file overhaul, now includes standard appendices and clearer format
> probably no need for the full text of MIT and BSD as the short version is preferred and already used
we still use the full text but this appears to be standard practice in other projects, and safer
> LICENSE is missing:
>  riak (see ./software/nosql/src/main/resources/brooklyn/entity/nosql/riak/vm.args + others)
these files are *our* …
> Update for 0.8.0 release

- README.md
Fixing link to developer guide.
> Fix broken link in top level README

- core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicExternalConfigSupplierRegistry.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/internal/ExternalConfigSupplierRegistryTest.java
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java
Replaces https://github.com/apache/incubator-brooklyn/pull/886
> Feature: external config fix / tests

- core/src/main/java/org/apache/brooklyn/enricher/stock/Propagator.java
- core/src/test/java/org/apache/brooklyn/enricher/stock/SensorPropagatingEnricherTest.java
See comments in https://github.com/apache/incubator-brooklyn/pull/888
> Add testSensorPropagatedWhenMappingUsedSameNameButDifferentType

- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java
Add synchronization and checks for duplicate rules in addPermission for the `JcloudsLocationSecurityGroupCustomizer` as used by Clocker. When deploying to OpenStack, duplicate rules will cause the `addPermission` method to fail, if the customizer is called in parallel on the same group. So, we serialize the calls with a `synchronized` block, and inside the critical section we make sure to only add rules that are not already present.
> Fixing JcloudsLocationSecurityGroupCustomizer on OpenStack

- core/src/main/java/org/apache/brooklyn/core/mgmt/persist/FileBasedObjectStore.java
- change method to use java.nio.file.Files
- add condition to delete existing destFile
> Fix FileBasedObjectStore#moveFile

- core/src/main/java/org/apache/brooklyn/core/mgmt/persist/FileBasedObjectStore.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessorWriterTest.java
- utils/common/src/main/java/org/apache/brooklyn/util/time/Time.java
See discussion in https://github.com/apache/incubator-brooklyn/pull/891, @alexmuntean 
Also fixes compilation error in o.a.b.util.time.Time, introduced in commit a340dbc311c19aef84c6b98d4d91b7776932212a
> log when atomic file move not possible

- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraDatacenterImpl.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraFabricImpl.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNode.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNodeImpl.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNodeSshDriver.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraDatacenterIntegrationTest.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraDatacenterLiveTest.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraDatacenterRebindIntegrationTest.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraDatacenterTest.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraFabricTest.java
- software/nosql/src/test/java/org/apache/brooklyn/entity/nosql/cassandra/CassandraNodeIntegrationTest.java
See each individual commit for details.
> Fix cassandra for use in private network

- software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/NativeWindowsScriptRunner.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelper.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessStreamsTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/DoNothingWinRmSoftwareProcessDriver.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsIntegrationTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinrmStreamsLiveTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelperUnitTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelperUnitTest.java
- Refactor AbstractSoftwareProcessWinrmDriver implementation like AbstractSoftwareProcessSshDriver
- ScriptHelperUnitTest exit code test
> Capture exit code in AbstractSoftwareProcessWinrmDriver

- core/src/main/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessor.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedObjectStoreTest.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessorWriterTest.java
- core/src/test/java/org/apache/brooklyn/core/mgmt/persist/ListeningObjectStore.java
- utils/common/src/main/java/org/apache/brooklyn/util/io/FilePermissions.java
- utils/common/src/main/java/org/apache/brooklyn/util/io/FileUtil.java
- utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java
On my machine this improved performance from 34903 accessor put() calls
per second to 61553 using the new implementation.
> Move to java7 setPosixFilePermissions

- docs/guide/yaml/winrm/index.md
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelper.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinrmExitStatusLiveTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinrmStreamsLiveTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WindowsTestFixture.java
- usage/camp/pom.xml
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/WindowsYamlLiveTest.java
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/echoArg.bat
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/echoFreemarkerMyarg.bat
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/echoFreemarkerMyarg.ps1
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/echoMyArg.ps1
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/exit0.bat
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/exit0.ps1
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/exit1.bat
- usage/camp/src/test/resources/org/apache/brooklyn/camp/brooklyn/exit1.ps1
- usage/launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/AbstractBlueprintTest.java
- usage/launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/Windows7zipBlueprintLiveTest.java
- usage/launcher/src/test/resources/7zip-catalog.yaml
- usage/launcher/src/test/resources/install7zip.ps1
For review only at this point - @bostko
> WinRM live tests

- software/database/src/main/resources/org/apache/brooklyn/entity/database/mssql/installmssql.ps1
pass the exit code from the install command to the install script
@nakomis could you review that please.
> MS SQL blueprint - improve installation script

- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java
> more tests for $brooklyn:external, clarifying DSL usage in location block

- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/MongoDBClientSupport.java
- isRunning() check uses ping() during the restart phase
- ping() must complete in a reasonable amount of time since
it is invoked against stopped entities too
- lowering the MongoClient timeouts, because default values are too 
high when used inside ping()
> BROOKLYN-175 Fixing MongoDB restart() phase

- docs/guide/yaml/winrm/index.md
- Remove the unnecessary Invoke-Command
> Powershell scripting documentation

- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlRebindTest.java
> Fix catalog item disabled/deprecated test

- usage/test-support/src/main/java/org/apache/brooklyn/test/HttpTestUtils.java
tested this locally as part of the proposed test framework
> pass flags to assertContentEventuallyMatches() for setting timeout

- software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/tomcat/TomcatServer.java
Have checked integration tests pass.
> Update Tomcat 7 download version

- karaf/features/src/main/resources/.gitignore
- karaf/pom.xml
- parent/pom.xml
Fix a few errors while loading the project in eclipse introduced by a recent karaf related PR.
> Fix eclipse m2e problems

- usage/rest-client/src/test/java/org/apache/brooklyn/rest/client/ApplicationResourceIntegrationTest.java
- usage/rest-client/src/test/java/org/apache/brooklyn/rest/client/BrooklynApiRestClientTest.java
- usage/rest-server/src/main/java/org/apache/brooklyn/rest/resources/LocationResource.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTest.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/EntityResourceTest.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/SensorResourceTest.java
- usage/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ServerShutdownTest.java
- usage/test-support/src/main/java/org/apache/brooklyn/test/HttpTestUtils.java
- utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java
- utils/common/src/main/java/org/apache/brooklyn/util/http/HttpAsserts.java
- utils/common/src/test/java/org/apache/brooklyn/test/AssertsTest.java
> expand assertions and http assertions for string containment, updating rest tests

- usage/camp/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlAppTest.java
See test case for details, special flags handling was resetting the encountered catalog ids stack.
/cc @aledsage
> Prevent catalog recursion in $brooklyn:memberSpec

- core/src/main/java/org/apache/brooklyn/core/config/ConfigKeys.java
- core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java
- core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java
- core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java
- core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/SshTool.java
- core/src/test/java/org/apache/brooklyn/core/config/ConfigKeysTest.java
- core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationReuseIntegrationTest.java
- core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationSshToolTest.java
- core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/java/JavaOptsTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/EntitySshToolTest.java
- software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/StartStopSshDriverTest.java
- software/webapp/src/test/java/org/apache/brooklyn/entity/proxy/nginx/NginxRebindWithHaIntegrationTest.java
Adds SshMachineLocation.SSH_TOOL_CLASS
- Deprecates SshTool.PROP_TOOL_CLASS
- Adds tests
> SshTool choice

- core/src/test/java/org/apache/brooklyn/util/core/task/DynamicSequentialTaskTest.java
Only changes the test code; comments very welcome, otherwise I'll merge it once jenkins confirms it builds.
> DynamicSequentialTaskTest: don’t wait forever

- usage/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java
> Fix mime-type typo

- core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java
These were logged at `info`. Switch to `debug`.
> Vault HTTP requests were logged at too high level

- docs/website/documentation/faq.md
Added a Problems section in faq.md describing how to increase ulimit.
@rdowner please advice whether this is a good place for `increasing ulimit'.
> Add documentation for the "unable to create new native thread" problem

- core/src/main/java/org/apache/brooklyn/util/core/http/HttpTool.java
- core/src/main/java/org/apache/brooklyn/util/core/http/HttpToolResponse.java
- docs/guide/misc/release-notes.md
PR follow-up to comment https://github.com/apache/incubator-brooklyn/pull/994#discussion_r44706399
> Restore old HttpTool / Response  for backward compatibility

- pom.xml
Updating validation api.
I am adding [brooklyn-tosca-transformer](https://github.com/cloudsoft/brooklyn-tosca/tree/master/brooklyn-tosca-transformer) to incubator-brooklyn. I built a uber jar and I added it to dropins folder, but I found a problem with this dependency so I have updated it.
> Updating Validation api version

- core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java
- core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java
- core/src/main/java/org/apache/brooklyn/util/core/ResourcePredicates.java
- core/src/main/java/org/apache/brooklyn/util/core/ResourceUtils.java
- examples/simple-web-cluster/src/main/java/org/apache/brooklyn/demo/WebClusterDatabaseExampleApp.java
- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooser.java
- software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/couchbase/CouchbaseNodeImpl.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/elasticsearch/ElasticSearchNode.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/mongodb/AbstractMongoDBServer.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/redis/RedisStore.java
- software/nosql/src/main/java/org/apache/brooklyn/entity/nosql/redis/RedisStoreImpl.java
- software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7Server.java
- software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/tomcat/TomcatServer.java
- usage/camp/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java
Things I've had stashed for a while.
> Minor miscellaneous additions

- parent/pom.xml
Useful for writing tests in downstream projects.
> Install tests sources in maven repo

- core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java
- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Reduce the risk of logging secrets, by using `Sanitizer.sanitize`
> Sanitize log messages

- core/src/main/java/org/apache/brooklyn/enricher/stock/Aggregator.java
- core/src/main/java/org/apache/brooklyn/enricher/stock/Enrichers.java
This addition enables the creation of a sensor, defined in YAML, to set its value based on whether a quorum of entities has has the necessary source sensor value.
Example:
```
name: Quorum Check Test
location: localhost
services:
- type: org.apache.brooklyn.entity.group.DynamicCluster
name: Cluster
brooklyn.config:
initialSize: 5
memberSpec:
$brooklyn:entitySpec:
type: org.apache.brooklyn.entity.software.base.EmptySoftwareProcess
name: Cluster Member
brooklyn.enrichers:
- type: org.apache.brooklyn.enricher.stock.Aggregator
brooklyn.config:
uniqueTag: service-all-is-up-aggregator
enricher.transformation.untyped: "isQuorate"
quorum.check.type: "allAndAtLeastOne"
quorum.total.size: $brooklyn:config("cluster.initial.size")
enricher.aggregator.excludeBlank: true …
```
> Add quorum check enricher and aggregator

- docs/guide/yaml/advanced-example.md
- docs/guide/yaml/example_yaml/brooklyn-elasticsearch-catalog.bom
- docs/guide/yaml/example_yaml/brooklyn-elk-catalog.bom
- docs/guide/yaml/example_yaml/brooklyn-kibana-catalog.bom
- docs/guide/yaml/example_yaml/brooklyn-logstash-catalog.bom
- docs/guide/yaml/index.md
- utils/common/src/main/java/org/apache/brooklyn/util/collections/CollectionFunctionals.java
Added some advanced YAML examples and made a CollectionFunctionals constructor public
> Added some advanced YAML examples

- core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/JavaBrooklynClassLoadingContext.java
We encountered this error when there were a Java entity in `lib/dropins` that still referenced the old `brooklyn.entity.basic.StartableApplication" (i.e. it had not been recompiled, with its source code updated).
The consequence was that `GET /v1/catalog/applications` failed, so no catalog items were displayed in the web-console. Also, the exception gives no indication of which catalog item the error came from (we unpacked all the jars, and did a string search across them to find it!).
With this fix, we'll get the log.debug that says which catalog item the error came from. The catalog item will be excluded from the list, and the other catalog items returned.
Ideally I'd like something better than just a `log.debug` to tell the user of this serious problem. Not convinced that …
> tryLoadClass: return optional.absent on NoClassDefFoundError

- software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlNode.java
- software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlNodeImpl.java
- software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlSshDriver.java
Cherry-picks same commits that were merged to `master` in #1098.
> (0.8.x backport) Misc MySQL 5.5.x and 5.6.x fixes

- software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/jboss/JBoss7ServerImpl.java
Cherry-picks commit 3b5b235f4b5d5ba71eb69722001b21d9f8e30260, merged to `master` back in September.
> (0.8.x backport) Fix jboss7 serviceUp

- core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java
- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
- locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationReleasePortForwardingTest.java
Ive made a change to PortForwarderAsync that makes it asynchronous.
Im looking for suggestions on how to verify this fix
Releates to https://github.com/brooklyncentral/advanced-networking/pull/86
> Making PortForwarderAsync Async

- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java
- locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizerTest.java
It is now possible to remove security groups permissions
> Ported some Clocker changes back to brooklyn.

- software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/JavaWebAppSshDriver.java
- usage/launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java
- usage/launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java
The `?00` permissions check is enforced on the link's target rather than the link itself.
> Brooklyn properties files may be symlinks

- core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java
Previously, `attributeWhenReady` would only abort if the entity was on fire.
Now `attributeWhenReady` will timeout after 1 minute if the entity is in the `STOPPING`, `STOPPED`, or `DESTROYED` state.
The call does not abort straight away because there is a chance that the dependent values may be needed in the `stop` phase, so this timeout gives such values a fair chance to be resolved before the resolution is canceled by way of a timeout.
> Add timeout to attributeWhenReady if entity is in destructive state

- core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java
- core/src/main/java/org/apache/brooklyn/location/byon/SingleMachineProvisioningLocation.java
- core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java
- core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java
- core/src/main/java/org/apache/brooklyn/util/core/task/system/internal/SystemProcessTaskFactory.java
- locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java
- software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineEntityImpl.java
And some other minor improvements as well.
> Fix cassandra on aws

- docs/guide/ops/cli/cli-ref-guide.md
- docs/guide/ops/cli/cli-usage-guide.md
- docs/guide/ops/cli/index.md
- docs/guide/ops/index.md
- docs/guide/ops/server-cli-reference.md
Includes CLI Reference Guide and Usage Guide.
> Add CLI documentation to the Operations Guide

- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultAppIdExternalConfigSupplier.java
@rdowner @aledsage can you review it.
> Fix `VaultAppIdExternalConfigSupplier` dynamic constructor

- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/entity/trait/Resizable.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/core/entity/trait/FailingEntity.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/core/entity/trait/FailingEntityImpl.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/core/test/entity/TestCluster.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/core/test/entity/TestClusterImpl.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
- brooklyn-server/policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java
- brooklyn-server/policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyMetricTest.java
- brooklyn-server/software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/autoscaling/AutoScalerPolicyNoMoreMachinesTest.java
- brooklyn-server/utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java
See https://issues.apache.org/jira/browse/BROOKLYN-212
> BROOKLYN-212 fix

- brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabricImpl.java
- When locations are defined at the YAML top-level, then ensure the
DynamicFabric finds those.
> Fix DynamicFabric locations

- brooklyn-library/software/database/src/main/java/org/apache/brooklyn/entity/database/mysql/MySqlNode.java
- brooklyn-library/software/database/src/main/resources/org/apache/brooklyn/entity/database/mysql/mysql.conf
Logs the login attempts as well.
@iyovcheva can you review
> Set error logging for MySqlNode

- brooklyn-library/software/messaging/src/main/java/org/apache/brooklyn/entity/messaging/kafka/KafkaClusterImpl.java
- brooklyn-library/software/webapp/src/main/java/org/apache/brooklyn/entity/webapp/ControlledDynamicWebAppClusterImpl.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/entity/EntityInternal.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabricImpl.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartableImpl.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/entity/stock/DataEntityImpl.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
- brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/SameServerEntityImpl.java
- brooklyn-server/test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCaseImpl.java
building on #1159 /cc @grkvlt @aledsage
> various fixes for start(Collection<Location>) implementations

- brooklyn-docs/guide/misc/release-notes.md
- brooklyn-server/api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java
- brooklyn-server/camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampResolver.java
- brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/typereg/AbstractTypePlanTransformer.java
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/typereg/BasicRegisteredType.java
as described in changes to release-notes.md
> for chained references, prefer outer catalog item id, and outer tags

- brooklyn-server/software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java
previously start showed a long list of subtasks; now they are grouped a bit more nicely i think.  see commit message for details.
this is quite a simple change.
> improve the start task tree shape

- brooklyn-library/pom.xml
- brooklyn-library/software/messaging/pom.xml
- exclude storm:carbonite transitive dependency
> Update storm remove redundant dependency - (duplicating in CXF)

- brooklyn-server/core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/util/core/task/DynamicSequentialTaskTest.java
the "fix" in #1171 didn't do everything, but provided enough clues to see the other culprit which this fixes, i think
> fix the nondet cancellation test race observed previously

- brooklyn-server/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/policy/CreatePasswordSensorIntegrationTest.java
- brooklyn-server/camp/camp-brooklyn/src/test/resources/EmptySoftwareProcessWithPassword.yaml
- brooklyn-server/core/src/main/java/org/apache/brooklyn/core/sensor/password/CreatePasswordSensor.java
- brooklyn-server/core/src/test/java/org/apache/brooklyn/core/sensor/password/CreatePasswordSensorTest.java
- brooklyn-server/utils/common/src/main/java/org/apache/brooklyn/util/text/Identifiers.java
- brooklyn-server/utils/common/src/test/java/org/apache/brooklyn/util/text/IdentifiersTest.java
A simple initialiser for creating passwords in yaml as a sensor
Added a password generating function in the Identifiers class which uses
SecureRandom
> Create Password Sensor
